// Generated by scripts/build-translations.cjs. Edit content translation files.
window.SITE_TRANSLATIONS = [
  [
    "Youssef Khaled",
    "يوسف خالد"
  ],
  [
    "BACKEND ENGINEER",
    "مهندس باك إند"
  ],
  [
    "Youssef Khaled | Laravel Backend Engineer Portfolio",
    "يوسف خالد | مهندس باك إند Laravel"
  ],
  [
    "Youssef Khaled | Laravel Backend Engineer",
    "يوسف خالد | مهندس باك إند Laravel"
  ],
  [
    "Skip to content",
    "عدّي للمحتوى"
  ],
  [
    "Main navigation",
    "التنقل الرئيسي"
  ],
  [
    "Youssef Khaled home",
    "يوسف خالد — الرئيسية"
  ],
  [
    "Open navigation",
    "افتح القائمة"
  ],
  [
    "Close navigation",
    "اقفل القائمة"
  ],
  [
    "Work",
    "المشاريع"
  ],
  [
    "Expertise",
    "المهارات"
  ],
  [
    "Experience",
    "الخبرة"
  ],
  [
    "Notes",
    "المقالات"
  ],
  [
    "Learn ↗",
    "اتعلّم ↗"
  ],
  [
    "About",
    "عني"
  ],
  [
    "Let’s talk",
    "نتكلم"
  ],
  [
    "BASED IN CAIRO · BUILDING BEYOND BORDERS",
    "من القاهرة · ببني للي أبعد"
  ],
  [
    "The logic behind",
    "الأساس اللي ورا"
  ],
  [
    "your next",
    "فكرتك"
  ],
  [
    "big idea.",
    "الجاية."
  ],
  [
    "I’m Youssef, a Laravel backend engineer. I turn complex business needs into reliable APIs, thoughtful systems, and products that work.",
    "أنا يوسف، مهندس باك إند Laravel. بحوّل احتياجات الشغل المعقّدة لـAPIs موثوقة، وأنظمة مدروسة، ومنتجات شغّالة بجد."
  ],
  [
    "Explore my work",
    "شوف شغلي"
  ],
  [
    "Download CV",
    "حمّل الـCV"
  ],
  [
    "Backend engineer. Problem solver.",
    "مهندس باك إند. بحب أحل المشاكل."
  ],
  [
    "Always a student of the craft.",
    "ودايمًا عندي حاجة جديدة أتعلّمها."
  ],
  [
    "Illustration of a Laravel backend connecting APIs, data, and background jobs",
    "رسم بيشرح اتصال Laravel بالـAPIs والداتا ومهام الخلفية"
  ],
  [
    "THE BACKEND, CONNECTED",
    "السيستم كله متوصّل"
  ],
  [
    "01 / SYSTEM VIEW",
    "٠١ / نظرة على السيستم"
  ],
  [
    "Web & mobile",
    "ويب وموبايل"
  ],
  [
    "THE EXPERIENCE",
    "تجربة المستخدم"
  ],
  [
    "THE ENGINE",
    "قلب السيستم"
  ],
  [
    "STRUCTURED DATA",
    "داتا منظّمة"
  ],
  [
    "Queue jobs",
    "مهام الخلفية"
  ],
  [
    "BACKGROUND WORK",
    "شغل في الخلفية"
  ],
  [
    "a little of what I do.php",
    "a little of what I do.php"
  ],
  [
    "Clean architecture. Real-world thinking.",
    "تصميم واضح. وتفكير عملي."
  ],
  [
    "GOOD PRODUCTS START WITH STRONG FOUNDATIONS",
    "كل منتج قوي بيبدأ بأساس صح"
  ],
  [
    "SCROLL TO EXPLORE ↓",
    "كمّل واكتشف ↓"
  ],
  [
    "MY EVERYDAY TOOLKIT",
    "أدواتي اليومية"
  ],
  [
    "01 / SELECTED WORK",
    "٠١ / مشاريع مختارة"
  ],
  [
    "Real problems.",
    "مشاكل حقيقية."
  ],
  [
    "Thoughtful solutions.",
    "وحلول مدروسة."
  ],
  [
    "A collection of Laravel backend systems, dashboards, APIs, and cloud-ready products built for real business operations.",
    "مجموعة أنظمة Laravel ولوحات تحكم وAPIs ومنتجات جاهزة للتشغيل، مبنية لاحتياجات شغل حقيقية."
  ],
  [
    "Project filters",
    "تصفية المشاريع"
  ],
  [
    "All Projects",
    "كل المشاريع"
  ],
  [
    "Evyx Products",
    "منتجات Evyx"
  ],
  [
    "Freelance",
    "عمل حر"
  ],
  [
    "Featured project case study",
    "دراسة حالة لمشروع مميز"
  ],
  [
    "Featured Case Study",
    "دراسة حالة مميزة"
  ],
  [
    "Role:",
    "دوري:"
  ],
  [
    "View Case Study",
    "افتح دراسة الحالة"
  ],
  [
    "View Details",
    "تفاصيل المشروع"
  ],
  [
    "Evyx Projects",
    "مشاريع Evyx"
  ],
  [
    "Freelance Projects",
    "مشاريع العمل الحر"
  ],
  [
    "No projects in this category.",
    "مفيش مشاريع في التصنيف ده."
  ],
  [
    "02 / WHAT I BRING",
    "٠٢ / اللي بقدّمه"
  ],
  [
    "Built for the whole backend.",
    "كل جزء في الباك إند ليه حساب."
  ],
  [
    "REST APIs",
    "REST APIs"
  ],
  [
    "Admin Dashboards",
    "لوحات التحكم"
  ],
  [
    "Authentication & Roles",
    "تسجيل الدخول والصلاحيات"
  ],
  [
    "Payment Flows",
    "عمليات الدفع"
  ],
  [
    "Queues & Jobs",
    "Queues & Jobs"
  ],
  [
    "Reports & Analytics",
    "التقارير والتحليلات"
  ],
  [
    "Database Design",
    "تصميم قواعد البيانات"
  ],
  [
    "Notifications",
    "الإشعارات"
  ],
  [
    "Build predictable endpoints with validation, resources, authentication, and clean client contracts.",
    "ببني Endpoints بسلوك واضح، وتحقق من المدخلات، وتسجيل دخول، وعقد مفهوم للعميل."
  ],
  [
    "Create operational panels that help teams manage records, workflows, reports, and product data.",
    "بعمل لوحات تحكم تساعد الفريق يدير السجلات ومراحل الشغل والتقارير وداتا المنتج."
  ],
  [
    "Implement secure access flows, permissions, policies, and role-based user experiences.",
    "بنفّذ دخول آمن وصلاحيات وPolicies وتجربة مناسبة لدور كل مستخدم."
  ],
  [
    "Design transaction-aware logic with webhook handling, status tracking, and failure-safe workflows.",
    "بصمّم منطق للمعاملات، ومعالجة Webhooks، وتتبع الحالات، والتعامل مع الفشل."
  ],
  [
    "Move heavy or delayed work into reliable background jobs for reports, notifications, and processing.",
    "بنقل الشغل التقيل أو المؤجّل لمهام في الخلفية، زي التقارير والإشعارات والمعالجة."
  ],
  [
    "Structure backend data for useful KPIs, operational dashboards, and query-friendly reporting.",
    "بنظّم الداتا عشان تطلع منها مؤشرات مفيدة ولوحات تشغيل وتقارير سهلة الاستعلام."
  ],
  [
    "Design maintainable schemas, relationships, constraints, indexing, and performance-aware queries.",
    "بصمّم جداول وعلاقات وقيود وفهارس واستعلامات تراعي الأداء وسهولة التطوير."
  ],
  [
    "Build in-app and external notification flows that are triggered from real product events.",
    "ببني إشعارات جوّه التطبيق وخارجه، مرتبطة بالأحداث الحقيقية في المنتج."
  ],
  [
    "03 / THE JOURNEY",
    "٠٣ / الرحلة"
  ],
  [
    "Experience that adds up.",
    "خبرة بتتبني خطوة بخطوة."
  ],
  [
    "A focused timeline of backend leadership, Laravel product delivery, mentoring, and technical content creation.",
    "رحلتي في قيادة تطوير الباك إند، وتسليم منتجات Laravel، والتدريس وصناعة المحتوى التقني."
  ],
  [
    "Remote Laravel Backend Developer",
    "مطوّر باك إند Laravel عن بُعد"
  ],
  [
    "Riyadh, Saudi Arabia",
    "الرياض، السعودية"
  ],
  [
    "Cairo, Egypt",
    "القاهرة، مصر"
  ],
  [
    "Team Leader Back-end Developer",
    "قائد فريق تطوير الباك إند"
  ],
  [
    "Evyx Company",
    "شركة Evyx"
  ],
  [
    "Full-Stack Developer",
    "مطوّر Full-Stack"
  ],
  [
    "YesOoh Company",
    "شركة YesOoh"
  ],
  [
    "Assistant Instructor",
    "مساعد مدرّس"
  ],
  [
    "Freelance Developer",
    "مطوّر مستقل"
  ],
  [
    "Independent",
    "عمل مستقل"
  ],
  [
    "Back-end Track Instructor",
    "مدرّس مسار الباك إند"
  ],
  [
    "Telegram Channel",
    "قناة تيليجرام"
  ],
  [
    "Content Creator",
    "صانع محتوى"
  ],
  [
    "YouTube Channel",
    "قناة يوتيوب"
  ],
  [
    "Dec '24 — Present",
    "ديسمبر ٢٠٢٤ — حتى الآن"
  ],
  [
    "Jan '23",
    "يناير ٢٠٢٣"
  ],
  [
    "Jan '22",
    "يناير ٢٠٢٢"
  ],
  [
    "Jan '21 — Present",
    "يناير ٢٠٢١ — حتى الآن"
  ],
  [
    "Jan '22 — Present",
    "يناير ٢٠٢٢ — حتى الآن"
  ],
  [
    "Developed authentication, database, workflow, and integration modules.",
    "طوّرت أجزاء تسجيل الدخول والداتا ومراحل الشغل والتكامل مع الخدمات."
  ],
  [
    "Built and maintained Laravel APIs for web and mobile applications.",
    "بنيت وطوّرت Laravel APIs لتطبيقات الويب والموبايل."
  ],
  [
    "Designed scalable Laravel backends and RESTful APIs for product systems.",
    "صمّمت أنظمة Laravel وRESTful APIs قابلة للنمو لمنتجات مختلفة."
  ],
  [
    "Collaborated with product and mobile teams to deliver features end-to-end.",
    "اشتغلت مع فرق المنتج والموبايل لتسليم المميزات من أولها لآخرها."
  ],
  [
    "Built a Laravel-based web app with user authentication and dynamic dashboards.",
    "بنيت تطبيق ويب بـLaravel فيه تسجيل دخول ولوحات تحكم ديناميكية."
  ],
  [
    "Implemented REST APIs and backend workflows for core features.",
    "نفّذت REST APIs ومنطق الباك إند للمميزات الأساسية."
  ],
  [
    "Delivered Laravel sessions and guided students through debugging tasks.",
    "قدّمت محاضرات Laravel وساعدت الطلبة يتتبّعوا الأخطاء ويصلحوها."
  ],
  [
    "Co-created backend learning content and practice exercises.",
    "شاركت في تجهيز محتوى تعليمي للباك إند وتمارين عملية."
  ],
  [
    "Completed multiple full-stack and backend projects for business workflows.",
    "نفّذت مشاريع Full-Stack وباك إند لاحتياجات تشغيل مختلفة."
  ],
  [
    "Maintained production-ready codebases, with deliverables shared on GitHub.",
    "طوّرت وصنت مشاريع جاهزة للتشغيل، مع نماذج شغل متاحة على GitHub."
  ],
  [
    "Taught PHP, Laravel, and MySQL fundamentals to junior developers.",
    "شرحت أساسيات PHP وLaravel وMySQL للمطوّرين المبتدئين."
  ],
  [
    "Structured practical backend tracks focused on real implementation.",
    "جهّزت مسارات باك إند بتركّز على التطبيق العملي."
  ],
  [
    "Published tutorials explaining Laravel backend concepts and project workflows.",
    "نشرت شروحات لمفاهيم Laravel وخطوات بناء المشاريع."
  ],
  [
    "Created practical videos to simplify backend development for learners.",
    "قدّمت فيديوهات عملية بتبسّط تطوير الباك إند للمتعلمين."
  ],
  [
    "04 / NOTES FROM THE WORKBENCH",
    "٠٤ / من دفتر الشغل"
  ],
  [
    "Build. Learn. Pass it on.",
    "ابني. اتعلّم. وشارك فهمك."
  ],
  [
    "Practical backend knowledge, shared in English and Arabic.",
    "معرفة عملية في الباك إند، بالعربي والإنجليزي."
  ],
  [
    "Behind the Code · A practical learning guide",
    "ورا الكود · دليل عملي بالمصري"
  ],
  [
    "AI writes code. Do you understand what’s behind it?",
    "الـAI يكتب كود. إنت فاهم اللي وراه؟"
  ],
  [
    "Eight backend foundations with examples, exercises, and references. Understand the decisions behind reliable code, and revisit them when you need to.",
    "٨ محاور في أساسيات الـBackend، بأمثلة وتمارين ومصادر. افهم القرارات اللي بتخلي الكود صح، وارجع راجعها وقت ما تحتاج."
  ],
  [
    "Explore the learning path ↙",
    "افتح خريطة التعلّم ↙"
  ],
  [
    "SYSTEM DESIGN",
    "تصميم الأنظمة"
  ],
  [
    "DATABASES",
    "قواعد البيانات"
  ],
  [
    "PERFORMANCE",
    "الأداء"
  ],
  [
    "Think beyond",
    "فكّر أبعد من"
  ],
  [
    "the endpoint.",
    "الـEndpoint."
  ],
  [
    "When requests",
    "لما الطلبات"
  ],
  [
    "collide.",
    "تتزاحم."
  ],
  [
    "Ready for",
    "جاهز للي"
  ],
  [
    "what’s next.",
    "جاي."
  ],
  [
    "System design foundations, caching patterns, and the decisions behind reliable backends.",
    "أساسيات تصميم الأنظمة وأنماط الكاش والقرارات اللي بتخلّي الباك إند موثوق."
  ],
  [
    "Transactions, concurrency, and locking in Laravel. Keep your data consistent under pressure.",
    "المعاملات والتزامن والأقفال في Laravel. حافظ على اتساق الداتا تحت الضغط."
  ],
  [
    "Exploring how Laravel applications scale from a thousand users to millions.",
    "إزاي تطبيقات Laravel ممكن تكبر من ألف مستخدم لملايين."
  ],
  [
    "Read the guide ↗",
    "اقرأ الدليل ↗"
  ],
  [
    "Read the English PDF ↗",
    "اقرأ الـPDF الإنجليزي ↗"
  ],
  [
    "Explore the writing archive ↗",
    "تصفّح كل المقالات ↗"
  ],
  [
    "English & Arabic learning resources ↗",
    "مصادر التعلّم بالعربي والإنجليزي ↗"
  ],
  [
    "05 / THE PERSON BEHIND THE CODE",
    "٠٥ / الشخص اللي ورا الكود"
  ],
  [
    "Engineer by trade.",
    "مهندس بشغلي."
  ],
  [
    "Curious by nature.",
    "وفضولي بطبعي."
  ],
  [
    "I am Youssef Khaled Anwar, a Laravel Backend Developer with hands-on experience building product backends at Evyx and delivering freelance client systems. I focus on REST APIs, database design, admin dashboards, authentication, permissions, reports, transactions, and maintainable business logic. My goal is to write backend code that is clear for developers, useful for operations, and reliable for real users.",
    "أنا يوسف خالد أنور، مطوّر باك إند Laravel. عندي خبرة عملية في بناء منتجات Evyx وتسليم أنظمة لعملاء مستقلين. بركّز على الـAPIs وتصميم الداتا ولوحات التحكم وتسجيل الدخول والصلاحيات والتقارير والمعاملات. هدفي كود واضح للمطوّرين، مفيد للتشغيل، ويعتمد عليه المستخدم."
  ],
  [
    "Beyond backend development, I also work with data analysis and continue developing my skills as a junior cloud engineer.",
    "جنب الباك إند، بشتغل على تحليل البيانات وبطوّر مهاراتي كمهندس Cloud مبتدئ."
  ],
  [
    "How I add value to a team",
    "إزاي بضيف للفريق"
  ],
  [
    "Translate product requirements into clean backend modules and API contracts.",
    "بحوّل متطلبات المنتج لأجزاء باك إند واضحة وعقود APIs مفهومة."
  ],
  [
    "Build admin workflows that reduce manual work and improve operational visibility.",
    "ببني أدوات إدارة تقلّل الشغل اليدوي وتخلّي متابعة التشغيل أوضح."
  ],
  [
    "Design database structures and business logic that are easier to maintain and extend.",
    "بصمّم الداتا ومنطق الشغل بشكل أسهل في الصيانة والتطوير."
  ],
  [
    "Communicate technical decisions clearly with developers, designers, and product teams.",
    "بشرح القرارات التقنية بوضوح للمطوّرين والمصممين وفرق المنتج."
  ],
  [
    "Download full CV",
    "حمّل السيرة الذاتية"
  ],
  [
    "06 / LET’S CONNECT",
    "٠٦ / نتواصل"
  ],
  [
    "Have something in mind?",
    "عندك فكرة؟"
  ],
  [
    "Let’s build it right.",
    "نبنيها صح سوا."
  ],
  [
    "Send me the role, product idea, or technical scope, and I will respond with how I can help build the backend foundation.",
    "ابعتلي تفاصيل الفرصة أو فكرة المنتج أو نطاق الشغل، ونتكلم إزاي أقدر أساعد في بناء الباك إند."
  ],
  [
    "Email me",
    "ابعتلي إيميل"
  ],
  [
    "WhatsApp",
    "واتساب"
  ],
  [
    "Thoughtfully built. From Cairo, Egypt.",
    "مبني بعناية. من القاهرة، مصر."
  ],
  [
    "Back to top ↑",
    "لفوق تاني ↑"
  ],
  [
    "Back to top",
    "ارجع لأعلى الصفحة"
  ],
  [
    "Close case study",
    "اقفل دراسة الحالة"
  ],
  [
    "Problem",
    "المشكلة"
  ],
  [
    "My Role",
    "دوري"
  ],
  [
    "Solution",
    "الحل"
  ],
  [
    "Key Features",
    "أهم المميزات"
  ],
  [
    "Impact",
    "النتيجة"
  ],
  [
    "View GitHub",
    "شوف الكود على GitHub"
  ],
  [
    "Project preview",
    "صورة المشروع"
  ],
  [
    "Case study preview",
    "صورة دراسة الحالة"
  ],
  [
    "← Back to portfolio",
    "ارجع للبورتفوليو ←"
  ],
  [
    "BACKEND NOTES",
    "مقالات الباك إند"
  ],
  [
    "Backend notes | Youssef Khaled",
    "مقالات الباك إند | يوسف خالد"
  ],
  [
    "NOTES FROM THE WORKBENCH",
    "من دفتر الشغل"
  ],
  [
    "Ideas worth",
    "أفكار تستاهل"
  ],
  [
    "building on.",
    "نبني عليها."
  ],
  [
    "Practical notes on Laravel, databases, and system design. Lessons from building, learning, and teaching.",
    "ملاحظات عملية عن Laravel والداتا وتصميم الأنظمة. دروس من الشغل والتعلّم والتدريس."
  ],
  [
    "Find a topic",
    "دوّر على موضوع"
  ],
  [
    "Search notes, topics, or keywords…",
    "دوّر في المقالات أو اكتب كلمة…"
  ],
  [
    "All notes",
    "كل المقالات"
  ],
  [
    "System design",
    "تصميم الأنظمة"
  ],
  [
    "Databases",
    "قواعد البيانات"
  ],
  [
    "Performance",
    "الأداء"
  ],
  [
    "System Design Fundamentals",
    "أساسيات تصميم الأنظمة"
  ],
  [
    "A practical guide to backend architecture, caching patterns, and the foundations of reliable systems.",
    "دليل عملي لتصميم الباك إند وأنماط الكاش وأساسيات الأنظمة الموثوقة."
  ],
  [
    "Concurrency & Locking in Laravel",
    "التزامن والأقفال في Laravel"
  ],
  [
    "Transactions, row locks, and safe updates. Practical notes on keeping your data consistent.",
    "المعاملات وأقفال الصفوف والتحديثات الآمنة. ملاحظات عملية عشان الداتا تفضل متسقة."
  ],
  [
    "Scaling Laravel: 1K to 5M",
    "توسّع Laravel: من ألف لـ٥ مليون"
  ],
  [
    "Explore the architecture and performance decisions behind growing a Laravel application.",
    "افهم قرارات التصميم والأداء اللي ورا نمو تطبيق Laravel."
  ],
  [
    "No notes match your search. Try another keyword or choose All notes.",
    "مفيش مقالات مطابقة. جرّب كلمة تانية أو اختار كل المقالات."
  ],
  [
    "Browse English & Arabic downloads ↗",
    "تصفّح التحميلات بالعربي والإنجليزي ↗"
  ],
  [
    "Youssef Khaled · Backend engineering, shared.",
    "يوسف خالد · بنشارك فهم الباك إند."
  ],
  [
    "Let’s talk ↗",
    "نتكلم ↗"
  ],
  [
    "LEARNING RESOURCES",
    "مصادر التعلّم"
  ],
  [
    "Learning resources | Youssef Khaled",
    "مصادر التعلّم | يوسف خالد"
  ],
  [
    "THE KNOWLEDGE HUB",
    "مساحة التعلّم"
  ],
  [
    "Good knowledge.",
    "معرفة مفيدة."
  ],
  [
    "Shared openly.",
    "بنشاركها مع الكل."
  ],
  [
    "Backend engineering resources in English and Arabic. Read the source notes or download a PDF for later.",
    "مصادر لتعلّم الباك إند بالعربي والإنجليزي. اقرأ الملاحظات أو حمّل PDF ترجع له بعدين."
  ],
  [
    "Transactions, row locks, and safe updates for real-world application workflows.",
    "المعاملات وأقفال الصفوف والتحديثات الآمنة في تطبيقات عملية."
  ],
  [
    "A practical exploration of application growth, architecture, and performance.",
    "شرح عملي لنمو التطبيقات وتصميمها وتحسين أدائها."
  ],
  [
    "English",
    "الإنجليزية"
  ],
  [
    "Read notes ↗",
    "اقرأ الملاحظات ↗"
  ],
  [
    "Download PDF ↓",
    "حمّل PDF ↓"
  ],
  [
    "Explore backend notes ↗",
    "تصفّح مقالات الباك إند ↗"
  ],
  [
    "Behind the Code",
    "ورا الكود"
  ],
  [
    "A learning space with Youssef Khaled",
    "مساحة تعلّم مع يوسف خالد"
  ],
  [
    "Learning path",
    "خريطة التعلّم"
  ],
  [
    "All articles",
    "كل المقالات"
  ],
  [
    "Portfolio",
    "البورتفوليو"
  ],
  [
    "Understand the foundations. Build on them.",
    "نفهم الأساس. ونبني عليه."
  ],
  [
    "AI can write code.",
    "الـAI يكتب كود."
  ],
  [
    "Do you",
    "إنت"
  ],
  [
    "understand the system?",
    "فاهم اللي وراه؟"
  ],
  [
    "Code can be written in seconds. But who defines the requirements, protects the data, and spots a failure? Here, we learn backend engineering through understanding and decisions, in plain language.",
    "الكود ممكن يتكتب في ثواني. بس مين هيحدّد المطلوب، ويحمي الداتا، ويعرف الغلط لما يحصل؟ هنا بنتعلّم الـBackend من زاوية الفهم والقرار، بالمصري ومن غير تعقيد."
  ],
  [
    "Start with the foundations",
    "نبدأ من الأساس"
  ],
  [
    "Explore the learning path",
    "شوف خريطة التعلّم"
  ],
  [
    "8 topics · Laravel examples · Learn at your own pace",
    "٨ محاور · أمثلة Laravel · قراءة وتطبيق على مهلك"
  ],
  [
    "From writing code → to understanding systems",
    "من كتابة الكود ← لفهم السيستم"
  ],
  [
    "Understand the problem",
    "افهم المطلوب"
  ],
  [
    "What are the problem and its boundaries?",
    "إيه المشكلة؟ وإيه حدود الحل؟"
  ],
  [
    "Choose and design",
    "اختار وصمّم"
  ],
  [
    "What can go wrong? Why this approach?",
    "إيه اللي ممكن يغلط؟ وليه الحل ده؟"
  ],
  [
    "Test and review",
    "اختبر وراجع"
  ],
  [
    "Where is the evidence it behaves correctly?",
    "فين الدليل إن السلوك صح؟"
  ],
  [
    "Be able to explain your decisions.",
    "الهدف إنك تقدر تشرح قرارك."
  ],
  [
    "Even if you did not write every line.",
    "حتى لو مش إنت اللي كتبت كل سطر."
  ],
  [
    "8",
    "٨"
  ],
  [
    "1",
    "١"
  ],
  [
    "foundational topics",
    "محاور أساسية"
  ],
  [
    "project connecting the ideas",
    "مشروع بيربط الأفكار"
  ],
  [
    "Plain-language explanations · Technical vocabulary",
    "شرح بالمصري · مصطلحات بالإنجليزي"
  ],
  [
    "A reference to come back to",
    "مرجع ترجع له وقت ما تحتاج"
  ],
  [
    "START HERE",
    "ابدأ من هنا"
  ],
  [
    "A small roadmap. A stronger foundation.",
    "خريطة صغيرة. أساس يفرق."
  ],
  [
    "Learning PHP or Laravel? Follow the path in order.",
    "لو بدأت تتعلّم PHP أو Laravel، امشي بالترتيب."
  ],
  [
    "Revisiting a topic? Jump straight to its lesson.",
    "ولو بتراجع حاجة معينة، ادخل على محورها مباشرة."
  ],
  [
    "What are you looking for?",
    "بتدور على إيه؟"
  ],
  [
    "Try: authorization, SQL, testing…",
    "جرّب: صلاحيات، SQL، اختبارات…"
  ],
  [
    "Filter learning topics",
    "تصفية محاور التعلّم"
  ],
  [
    "All topics",
    "كل المحاور"
  ],
  [
    "Reviewed ✓",
    "راجعت ✓"
  ],
  [
    "Guide contents",
    "فهرس الدليل"
  ],
  [
    "ON YOUR DESK",
    "على مكتبك"
  ],
  [
    "Guide topics",
    "محاور الدليل"
  ],
  [
    "Put it all together",
    "اجمع اللي اتعلّمته"
  ],
  [
    "Topics reviewed",
    "محاور راجعتها"
  ],
  [
    "Progress is saved in this browser only. It is a review tracker, not a skills assessment.",
    "التقدّم بيتحفظ على نفس المتصفح بس، ومش معناه تقييم لمستواك."
  ],
  [
    "Start the first topic →",
    "ابدأ أول محور ←"
  ],
  [
    "Continue with an unreviewed topic →",
    "كمّل أول محور لسه ما راجعتوش ←"
  ],
  [
    "All topics reviewed. Try the project →",
    "راجعت كل المحاور. جرّب المشروع ←"
  ],
  [
    "Print the guide or save as PDF ↓",
    "اطبع الدليل أو احفظه PDF ↓"
  ],
  [
    "HOW TO USE THIS GUIDE",
    "طريقة استخدام الدليل"
  ],
  [
    "Read. Try. Explain it in your own words.",
    "اقرأ. جرّب. اشرحها بطريقتك."
  ],
  [
    "Each topic includes an idea, a workshop-booking scenario, and a question to answer before revealing a suggestion. Choose one topic and apply it; you do not need to finish everything at once.",
    "كل محور فيه فكرة، وموقف من مشروع حجز ورش، وسؤال تجرّب تجاوبه قبل ما تفتح الإجابة. مش لازم تخلص الكل مرة واحدة؛ اختار محور وطبّقه."
  ],
  [
    "Examples refer to Laravel 12.x. Check your project's version before applying them. Content last reviewed:",
    "الأمثلة بتشير لـLaravel 12.x. راجع توثيق إصدار مشروعك قبل التطبيق. آخر مراجعة للمحتوى:"
  ],
  [
    "September 11, 2026",
    "١١ سبتمبر ٢٠٢٦"
  ],
  [
    "· About 4 minutes",
    "· ٤ دقايق تقريبًا"
  ],
  [
    "· About 5 minutes",
    "· ٥ دقايق تقريبًا"
  ],
  [
    "· About 6 minutes",
    "· ٦ دقايق تقريبًا"
  ],
  [
    "Key terms",
    "مصطلحات المحور"
  ],
  [
    "The idea, simply",
    "الفكرة ببساطة"
  ],
  [
    "FROM THE BOOKING PROJECT",
    "من مشروع الحجز"
  ],
  [
    "When reviewing AI-generated code",
    "وإنت بتراجع كود الـAI"
  ],
  [
    "PAUSE AND TRY IT",
    "وقف القراءة وجرّب"
  ],
  [
    "Thought it through? Reveal a suggested answer",
    "فكّرت؟ شوف إجابة مقترحة"
  ],
  [
    "Go deeper with the source:",
    "كمّل من المصدر:"
  ],
  [
    "A practical framework suggested in this guide. Adapt it to your project's rules.",
    "إطار عملي مقترح في الدليل. طبّقه على قواعد مشروعك."
  ],
  [
    "Direct link ↗",
    "رابط المحور ↗"
  ],
  [
    "CONNECT THE DOTS",
    "وصّل النقط ببعض"
  ],
  [
    "One project to test your understanding",
    "مشروع واحد يختبر فهمك"
  ],
  [
    "Build a booking API for a 20-seat workshop. Use AI for implementation if you like, but be ready to explain every decision. Work with local learning data.",
    "ابني API لحجز ورشة سعتها 20 مكان. استخدم الـAI في التنفيذ لو حابب، بس خليك قادر تشرح كل قرار. جرّب على داتا محلية للتعلّم."
  ],
  [
    "Define confirmation and cancellation rules, including what counts as an active booking.",
    "اكتب قواعد تأكيد وإلغاء الحجز، واتفق على معنى «حجز فعّال»."
  ],
  [
    "Design the database and API contract, and prevent access to other users' bookings.",
    "صمّم الجداول وعقد الـAPI، وامنع الوصول لحجوزات الآخرين."
  ],
  [
    "Test two requests for the last seat, repeated creation, and repeated cancellation.",
    "اختبر طلبين على آخر مكان، وطلب إنشاء متكرر، وإلغاء متكرر."
  ],
  [
    "Send a background notification and test job failure and repeated execution.",
    "ابعت إشعارًا في الخلفية، وجرّب فشل المهمة وإعادة تنفيذها."
  ],
  [
    "Measure queries and record signals that help investigate a failed request.",
    "قيس الاستعلامات، وسجّل إشارات تساعدك تتتبّع طلبًا فاشلًا."
  ],
  [
    "Document two decisions, an alternative for each, and why you chose against it.",
    "اكتب قرارين اخترتهم وبديلًا لكل واحد وليه مااخترتوش."
  ],
  [
    "Produce evidence, not just a repository:",
    "سلّم لنفسك دليل، مش مجرد Repo:"
  ],
  [
    "A description of the rules, failure-path tests, and a short explanation of trade-offs. If you can walk someone through the entire request journey, you are building understanding you can rely on.",
    "وصف للقواعد، اختبارات لحالات الفشل، وشرح قصير للتنازلات. لو تقدر تمشي حد في رحلة الطلب من أولها لآخرها، إنت بتبني فهم تقدر تعتمد عليه."
  ],
  [
    "Go deeper: explore the system design reference →",
    "عايز تتعمّق؟ افتح مرجع الـSystem Design ←"
  ],
  [
    "KEEP LEARNING TOGETHER",
    "نكمل تعلّم سوا"
  ],
  [
    "What should we unpack next?",
    "فيه نقطة محتاجة نفكّها أكتر؟"
  ],
  [
    "Suggest a topic or correction with an example or a source. Practical questions are a great starting point for explanations worth returning to.",
    "ابعت اقتراح موضوع أو تصحيح مع مثال أو مصدر. الأسئلة العملية هي أحسن بداية لشرح يستاهل نرجع له."
  ],
  [
    "Suggest a topic by email ↗",
    "اقترح موضوع بالإيميل ↗"
  ],
  [
    "Behind the Code · Understand, apply, revisit.",
    "ورا الكود · نفهم، نطبّق، ونرجع نراجع."
  ],
  [
    "Behind the Code | Backend foundations in the AI era — Youssef Khaled",
    "ورا الكود | أساسيات الـBackend في عصر الـAI — يوسف خالد"
  ],
  [
    "Behind the Code — AI writes. You understand and decide.",
    "ورا الكود — الـAI يكتب. وإنت تفهم وتقرر."
  ],
  [
    "A practical guide to backend fundamentals in the AI era: eight topics with examples, exercises, and references.",
    "دليل عملي بالمصري: إيه اللي لازم تفهمه كـBackend Developer حتى لو الـAI بيكتب الكود؟ ٨ محاور بأمثلة وتمارين ومصادر للمراجعة."
  ],
  [
    "A backend reference: from understanding requirements to reviewing code and running systems. Examples, exercises, and direct topic links.",
    "مرجع بالمصري لأساسيات الـBackend: من فهم المشكلة لحد مراجعة الكود وتشغيل السيستم. أمثلة وتمارين وروابط مباشرة لكل محور."
  ],
  [
    "Working systems. Thoughtful engineering.",
    "أنظمة شغّالة. وهندسة مدروسة."
  ],
  [
    "16 projects",
    "١٦ مشروع"
  ],
  [
    "Explore the collection",
    "اكتشف المشاريع"
  ],
  [
    "ENGINEERING WITH INTENT",
    "هندسة بهدف واضح"
  ],
  [
    "From the first request to the last mile.",
    "من أول طلب لآخر خطوة."
  ],
  [
    "Built with care. Designed to keep growing.",
    "مبني بعناية. وجاهز يكبر."
  ],
  [
    "Portfolio of Youssef Khaled, a Laravel Backend Engineer focused on REST APIs, admin dashboards, database design, business logic, queues, reports, and production-ready backend systems.",
    "بورتفوليو يوسف خالد، مهندس باك إند Laravel متخصص في الـAPIs ولوحات التحكم وتصميم الداتا ومنطق الشغل والمهام والتقارير."
  ],
  [
    "Laravel backend portfolio featuring Evyx product systems, freelance builds, REST APIs, dashboards, and production-focused backend engineering.",
    "بورتفوليو Laravel فيه منتجات Evyx ومشاريع مستقلة وAPIs ولوحات تحكم وهندسة باك إند للتشغيل الفعلي."
  ],
  [
    "Practical backend engineering notes and Laravel learning resources by Youssef Khaled, in English and Arabic.",
    "ملاحظات عملية في الباك إند ومصادر لتعلّم Laravel مع يوسف خالد، بالعربي والإنجليزي."
  ],
  [
    "SOFTWARE ENGINEER",
    "مهندس برمجيات"
  ],
  [
    "YOUSSEF KHALED / SOFTWARE ENGINEER",
    "يوسف خالد / مهندس برمجيات"
  ],
  [
    "Ideas into",
    "أفكار تصبح"
  ],
  [
    "interfaces.",
    "تجارب."
  ],
  [
    "Code into",
    "وكود يصنع"
  ],
  [
    "impact.",
    "أثرًا."
  ],
  [
    "Youssef Khaled | Software Engineer Portfolio",
    "يوسف خالد | مهندس برمجيات"
  ],
  [
    "Youssef Khaled | Software Engineer",
    "يوسف خالد | مهندس برمجيات"
  ],
  [
    "I’m Youssef, a software engineer. I connect thoughtful interfaces with reliable systems, turning complex business needs into web applications, APIs, and products that work.",
    "أنا يوسف، مهندس برمجيات. بربط واجهات مدروسة بأنظمة موثوقة، وبحوّل احتياجات الشغل المعقّدة لتطبيقات وتجارب ومنتجات شغّالة بجد."
  ],
  [
    "Software engineer. Problem solver.",
    "مهندس برمجيات. بحب أحل المشاكل."
  ],
  [
    "ENGINEERING PLAYGROUND",
    "مساحة التجربة الهندسية"
  ],
  [
    "01 / LIVE DEMO",
    "٠١ / تجربة تفاعلية"
  ],
  [
    "FROM A CLICK TO A RESPONSE",
    "من ضغطة لحد الاستجابة"
  ],
  [
    "Run a request",
    "جرّب رحلة الطلب"
  ],
  [
    "React UI",
    "واجهة React"
  ],
  [
    "App services",
    "خدمات التطبيق"
  ],
  [
    "An illustrative flow. Press run to follow a request.",
    "تجربة توضيحية. اضغط الزر وتابع رحلة الطلب."
  ],
  [
    "MY ENGINEERING TOOLKIT",
    "أدواتي في هندسة البرمجيات"
  ],
  [
    "01 / React UI sends a request.",
    "٠١ / واجهة React بتبعت الطلب."
  ],
  [
    "02 / Application services validate and process it.",
    "٠٢ / خدمات التطبيق بتراجع الطلب وتعالجه."
  ],
  [
    "03 / The database reads and persists data.",
    "٠٣ / قاعدة البيانات بتقرأ البيانات وتحفظها."
  ],
  [
    "04 / Background jobs handle follow-up work.",
    "٠٤ / المهام الخلفية بتكمّل الشغل."
  ],
  [
    "200 OK / Flow complete. Built to work together.",
    "200 OK / الرحلة اكتملت. أجزاء بتشتغل مع بعض."
  ],
  [
    "A collection of product systems, dashboards, APIs, and web applications built for real business operations.",
    "مجموعة من الأنظمة ولوحات التحكم والـAPIs وتطبيقات الويب، مبنية لاحتياجات شغل حقيقية."
  ],
  [
    "Find your kind of project",
    "دوّر على المشروع اللي يهمّك"
  ],
  [
    "Search projects, APIs, MySQL…",
    "ابحث باسم المشروع أو التقنية…"
  ],
  [
    "TechPack · Saudi Arabia",
    "تِك باك · السعودية"
  ],
  [
    "No projects found. Try another name or technology, or choose All Projects.",
    "مفيش مشاريع مطابقة. جرّب اسم أو تقنية تانية، أو اختار كل المشاريع."
  ],
  [
    "COMPANY PROJECTS / SAUDI ARABIA",
    "مشاريع الشركة / المملكة العربية السعودية"
  ],
  [
    "Technical Package",
    "تكنيكال باكدج"
  ],
  [
    "TechPack",
    "تِك باك"
  ],
  [
    "Technical Package (TechPack)",
    "تكنيكال باكدج (تِك باك)"
  ],
  [
    "Technical Package · Saudi Arabia",
    "تكنيكال باكدج · السعودية"
  ],
  [
    "Four backend projects from my work with the Saudi Arabia-based company.",
    "أربعة مشاريع باك إند من شغلي مع الشركة في المملكة العربية السعودية."
  ],
  [
    "My role ↗",
    "دوري في الشركة ↗"
  ],
  [
    "User application",
    "تطبيق المستخدم"
  ],
  [
    "Backend",
    "باك إند"
  ],
  [
    "Family tree",
    "شجرة العائلة"
  ],
  [
    "From interface to architecture.",
    "من الواجهة لبنية النظام."
  ],
  [
    "React & Web Interfaces",
    "React وتجارب الويب"
  ],
  [
    "Component-based interfaces with React, JavaScript, HTML, and CSS, connecting user interactions to application APIs.",
    "واجهات مبنية بمكوّنات React وJavaScript وHTML وCSS، بتربط تفاعل المستخدم بخدمات التطبيق."
  ],
  [
    ".NET & C#",
    ".NET وC#"
  ],
  [
    "Application development with C#, .NET, and ASP.NET Core, with a focus on structured services and clear API contracts.",
    "تطوير التطبيقات باستخدام C# و.NET وASP.NET Core، مع خدمات منظّمة وواجهات API واضحة."
  ],
  [
    "Software Design",
    "تصميم البرمجيات"
  ],
  [
    "Object-oriented programming, separation of concerns, and maintainable modules that keep software easier to extend.",
    "برمجة كائنية وفصل المسؤوليات، ومكوّنات سهلة الصيانة بتخلّي تطوير النظام وتوسيعه أبسط."
  ],
  [
    "Git & Collaboration",
    "Git والعمل الجماعي"
  ],
  [
    "Version control, focused changes, debugging, and clear communication throughout the development process.",
    "إدارة إصدارات الكود، وتغييرات واضحة، وحل المشاكل، وتواصل فعّال طول رحلة التطوير."
  ],
  [
    "A timeline of software delivery, backend engineering, mentoring, and technical content creation.",
    "رحلة في بناء البرمجيات وهندسة الباك إند، وتوجيه المطوّرين ومشاركة المعرفة."
  ],
  [
    "Projects: Personal Shipper, Albhkaly Family Tree, Afaq, and Hima Plus.",
    "المشاريع: Personal Shipper، وشجرة عائلة البهكلي، وآفاق، وHima Plus."
  ],
  [
    "Explore company projects ↗",
    "شوف مشاريع الشركة ↗"
  ],
  [
    "Read the Arabic guide ↗",
    "اقرأ الدليل العربي ↗"
  ],
  [
    "I am Youssef Khaled Anwar, a Software Engineer with hands-on experience building product backends at Technical Package in Saudi Arabia and Evyx in Egypt, alongside freelance client systems. I focus on REST APIs, database design, admin dashboards, authentication, permissions, reports, transactions, and maintainable business logic. My goal is to build software that is clear for developers, useful for operations, and reliable for real users.",
    "أنا يوسف خالد أنور، مهندس برمجيات بخبرة عملية في بناء الأنظمة مع تكنيكال باكدج في السعودية وEvyx في مصر، بجانب مشاريع العملاء المستقلة. بشتغل على الـAPIs وتصميم قواعد البيانات ولوحات الإدارة والصلاحيات والتقارير والمعاملات ومنطق الشغل. هدفي أبني برمجيات واضحة للمطوّرين، مفيدة للفرق، وموثوقة للمستخدمين."
  ],
  [
    "My toolkit spans React and JavaScript for interfaces, .NET and C# for application development, and Laravel and PHP for backend systems. I also explore data analysis and cloud engineering.",
    "أدواتي بتشمل React وJavaScript للواجهات، و.NET وC# لتطوير التطبيقات، وLaravel وPHP للباك إند. وبطوّر معرفتي كمان في تحليل البيانات وهندسة الكلاود."
  ],
  [
    "Translate product requirements into clear application modules, interfaces, and API contracts.",
    "أحوّل متطلبات المنتج لمكوّنات تطبيق واضحة، وواجهات مدروسة، وعقود API منظّمة."
  ],
  [
    "Send me the role, product idea, or technical scope, and I will respond with how I can help build the software foundation.",
    "ابعتلي تفاصيل الوظيفة أو فكرة المنتج أو المطلوب تقنيًا، ونتكلم إزاي أقدر أساعدك تبني أساس برمجي قوي."
  ],
  [
    "A backend platform that keeps legal consultation requests structured, secure, and operationally visible.",
    "منصة باك إند بتنظّم طلبات الاستشارات القانونية، وتحافظ على أمانها ووضوح متابعتها."
  ],
  [
    "Laravel backend architecture, API contracts, permissions, and admin workflow orchestration.",
    "تصميم بنية الباك إند بـLaravel، وعقود الـAPI والصلاحيات وتنظيم عمليات الإدارة."
  ],
  [
    "Request lifecycle engine with clear service states",
    "مراحل واضحة لطلبات الخدمة"
  ],
  [
    "Role-based permissions for lawyers, clients, and admins",
    "صلاحيات للمحامين والعملاء والإدارة"
  ],
  [
    "Notification triggers and dashboard operations",
    "إشعارات مرتبطة بالأحداث وعمليات لوحة التحكم"
  ],
  [
    "API contracts designed for mobile reliability",
    "عقود API مناسبة لتطبيقات الموبايل"
  ],
  [
    "Queue Jobs",
    "المهام الخلفية"
  ],
  [
    "Portfolio of Youssef Khaled, a Software Engineer working with React, .NET, C#, Laravel, PHP, REST APIs, databases, and reliable web applications.",
    "بورتفوليو يوسف خالد، مهندس برمجيات يعمل باستخدام React و.NET وC# وLaravel وPHP، لبناء تطبيقات ويب وخدمات API وأنظمة موثوقة."
  ],
  [
    "Software engineering portfolio featuring product systems, freelance builds, React, .NET, Laravel, APIs, and thoughtful web experiences.",
    "بورتفوليو هندسة برمجيات يضم أنظمة منتجات ومشاريع مستقلة وتجارب ويب، باستخدام React و.NET وLaravel."
  ],
  [
    "Evyx Product",
    "منتج Evyx"
  ],
  [
    "Albhkaly Family Tree",
    "شجرة عائلة البهكلي"
  ],
  [
    "Afaq",
    "آفاق"
  ],
  [
    "Legal consultation platform backend supporting client requests, lawyer/admin workflows, notifications, and structured service management.",
    "باك إند لمنصة استشارات قانونية، بيدير طلبات العملاء وعمليات المحامين والإدارة والإشعارات والخدمات."
  ],
  [
    "Legal service requests can become hard to track without clear roles, request states, and admin visibility.",
    "متابعة طلبات الخدمات القانونية بتحتاج أدوار واضحة وحالات طلب محددة ورؤية كاملة للإدارة."
  ],
  [
    "Implemented Laravel backend flows, API contracts, request lifecycle logic, permissions, and dashboard operations.",
    "نفّذت مسارات الباك إند بـLaravel، وعقود API ومراحل الطلب والصلاحيات وعمليات لوحة التحكم."
  ],
  [
    "A structured service-request backend with role-based access, notification triggers, and admin tools for managing consultations.",
    "باك إند منظّم لطلبات الخدمة، بصلاحيات حسب الدور وإشعارات وأدوات إدارة للاستشارات."
  ],
  [
    "Understand the problem before the solution",
    "افهم المشكلة قبل ما تكتب الحل"
  ],
  [
    "Foundations",
    "الأساسيات"
  ],
  [
    "The first sentence in a brief rarely tells the whole story. Turn it into clear rules you can test.",
    "المطلوب مش دايمًا هو أول جملة اتقالت لك. دورك تحوّل الكلام لقواعد واضحة تقدر تختبرها."
  ],
  [
    "“Build a booking system” is not enough to start. Who can book? Can they cancel? When is a booking confirmed? What happens when two people claim the last seat? Before choosing tools, write down the business rules and the states the system must prevent. Define the first release's limits too: expected usage, operating budget, and acceptable latency. Agree on these assumptions and revisit them; do not invent numbers.",
    "لو اتقال لك: اعمل نظام حجز، لسه ماعندكش متطلبات كفاية. مين بيحجز؟ ينفع يلغي؟ الحجز بيتأكد إمتى؟ وإيه اللي يحصل لو اتنين اختاروا آخر مكان؟ قبل اختيار الأدوات، اكتب قواعد الشغل والحالات اللي النظام لازم يمنعها. حدّد كمان حدود أول نسخة: عدد المستخدمين المتوقع، ميزانية التشغيل، ومستوى التأخير المقبول. دي افتراضات نتفق عليها ونراجعها، مش أرقام نألفها."
  ],
  [
    "Throughout this guide, we use a workshop with 20 seats. One invariant: confirmed bookings must never exceed capacity. One product decision: does a pending booking reserve a seat, and for how long? Those answers change both the data model and the behavior.",
    "هنمشي في الدليل بمثال حجز ورشة فيها 20 مكان. قاعدة أساسية: عدد الحجوزات المؤكدة مايزيدش عن السعة. وقاعدة محتاجة قرار من صاحب المنتج: هل الحجز المعلّق بيحجز مكان؟ ولمدة قد إيه؟ الإجابتين هيغيّروا تصميم الداتا والسلوك."
  ],
  [
    "If AI starts generating controllers and tables before addressing cancellation and confirmation, pause and write the scenarios. Well-organized code can implement the wrong rule very efficiently.",
    "لو الـAI بدأ يعمل Controllers وجداول قبل ما يسألك عن الإلغاء وتأكيد الحجز، وقف التنفيذ واكتب السيناريوهات الأول. الكود المنظّم ممكن ينفّذ قاعدة غلط بمنتهى الكفاءة."
  ],
  [
    "Write three acceptance criteria for booking a seat, and two questions to ask the product owner before implementation.",
    "اكتب 3 شروط لقبول ميزة الحجز، وسؤالين لازم تسألهم لصاحب المنتج قبل التنفيذ."
  ],
  [
    "Possible criteria: a signed-in user can book an available seat; they cannot confirm two bookings for the same workshop; confirmed bookings never exceed capacity. Ask when a booking becomes confirmed and how cancellations and pending-booking expiry work. The right answer depends on product rules, not the framework.",
    "شروط ممكنة: مستخدم مسجّل يحجز مكان متاح، ماينفعش يأكد حجزين لنفس الورشة، ومجموع الحجوزات المؤكدة مايتجاوزش السعة. اسأل: إمتى الحجز يبقى مؤكد؟ وإيه سياسة الإلغاء وانتهاء الحجز المعلّق؟ الإجابة الصح مرتبطة بقواعد المنتج، مش بالـFramework."
  ],
  [
    "I can describe success and failure before reading the implementation.",
    "أقدر أوصف النجاح والفشل قبل ما أبص على الكود."
  ],
  [
    "Reviewed: I can describe success and failure before reading the implementation.",
    "راجعت المحور: أقدر أوصف النجاح والفشل قبل ما أبص على الكود."
  ],
  [
    "Direct link: Understand the problem before the solution",
    "رابط مباشر: افهم المشكلة قبل ما تكتب الحل"
  ],
  [
    "Follow the request all the way through",
    "اعرف الـRequest بيروح فين"
  ],
  [
    "Foundations",
    "الأساسيات"
  ],
  [
    "An endpoint is an agreement with its clients: inputs, outcomes, errors, and retry behavior.",
    "الـEndpoint اتفاق بينك وبين اللي بيستخدمه: المدخلات، النتيجة، الأخطاء، وسلوك إعادة المحاولة."
  ],
  [
    "Understand the path from client to server, middleware, business logic, and storage. GET is for reading; a read link should not confirm a booking. POST can create a resource, but does not automatically prevent duplicates. Idempotency means repeating an operation does not add to its intended effect; it need not return an identical response. Agree on error formats, input limits, and pagination for lists.",
    "افهم رحلة الطلب من العميل، للسيرفر، للـMiddleware، لمنطق الشغل، وللداتا. GET للقراءة؛ ماينفعش رابط قراءة يأكد حجز. POST ممكن ينشئ مورد، لكنه مش بيمنع التكرار تلقائيًا. والـIdempotency معناها إن تكرار نفس العملية مايزوّدش أثرها المقصود، مش شرط يرجع نفس الـResponse بالحرف. اتفق على شكل الأخطاء وحدود المدخلات والـPagination لو بترجع قوائم."
  ],
  [
    "The server creates a booking, but the connection drops before the response arrives. The user tries again. You can design an idempotency key tied to the user and an input fingerprint, with atomic duplicate prevention. Repeating the same request returns the recorded outcome; reusing the key with different inputs is a conflict handled according to your API contract.",
    "العميل بعت حجز، والسيرفر نفّذه، لكن الشبكة قطعت قبل الرد. المستخدم ضغط تاني. نقدر نصمّم Idempotency key للعملية، مرتبط بالمستخدم وببصمة المدخلات، مع منع ذري لتكراره. إعادة نفس الطلب ترجع نتيجة العملية المسجّلة؛ إعادة المفتاح بمدخلات مختلفة تتعامل كحالة تعارض حسب عقد الـAPI."
  ],
  [
    "Review the API as a client. Are validation errors clear? Is invalid input distinguished from a conflict with booking state? What is the documented retry contract?",
    "بص على الـAPI كعميل: هل أخطاء الـValidation مفهومة؟ هل فيه فرق بين مدخلات غلط وتعارض مع حالة الحجز؟ وإيه العقد المكتوب لإعادة المحاولة؟"
  ],
  [
    "Two identical booking requests arrive simultaneously. Is checking for an existing booking before creating it enough?",
    "لو نفس طلب إنشاء الحجز وصل مرتين في نفس اللحظة، هل فحص وجود الحجز قبل الإنشاء كفاية؟"
  ],
  [
    "No. Both requests can pass the check before either writes. You need a database constraint or another suitable atomic mechanism, plus a clear contract for duplicate requests. Retries are part of the design, not just a button in the interface.",
    "لأ. الاتنين ممكن يعملوا الفحص قبل ما أي واحد يكتب. محتاج منع تكرار على مستوى الداتا أو آلية ذرية مناسبة، وعقد واضح للمفتاح والطلب المتكرر. إعادة المحاولة جزء من التصميم، مش مجرد زر في الواجهة."
  ],
  [
    "I can explain API behavior for success, errors, and retries.",
    "أقدر أشرح سلوك الـAPI في النجاح والغلط وإعادة المحاولة."
  ],
  [
    "Reviewed: I can explain API behavior for success, errors, and retries.",
    "راجعت المحور: أقدر أشرح سلوك الـAPI في النجاح والغلط وإعادة المحاولة."
  ],
  [
    "Direct link: Follow the request all the way through",
    "رابط مباشر: اعرف الـRequest بيروح فين"
  ],
  [
    "Protect your rules in the database",
    "احمي قواعدك جوّه الداتا"
  ],
  [
    "Data & security",
    "الداتا والأمان"
  ],
  [
    "Validation alone is not enough. Concurrent requests can break rules that passed a single-request test.",
    "الـValidation لوحده مش كفاية. اتنين Requests شغالين مع بعض ممكن يكسروا قاعدة كانت سليمة في اختبار فردي."
  ],
  [
    "Start with relationships and constraints: a user has bookings, and each booking belongs to a workshop. Use foreign keys and unique constraints that match product rules. A transaction groups related changes, but its presence alone does not prevent every concurrency issue. In Laravel, lockForUpdate inside a transaction can lock the record you coordinate on; locking and isolation details depend on your database.",
    "ابدأ بالعلاقات والقيود: المستخدم له حجوزات، والحجز تابع لورشة. استخدم Foreign keys وقيود Unique المناسبة لقواعد المنتج. الـTransaction بتجمع تغييرات مرتبطة، لكن وجودها لوحده مش ضمان ضد كل مشاكل التزامن. في Laravel تقدر تستخدم lockForUpdate داخل Transaction لقفل السجل اللي بتنسّق عليه؛ تفاصيل الأقفال والعزل بتعتمد على قاعدة البيانات."
  ],
  [
    "One seat remains and two people try to book it. An educational approach: lock the workshop row within a transaction, check availability, decrement it, and record the booking. Every capacity-changing path must follow the same coordination rule. Another option is an atomic conditional update that decrements only when capacity is positive, checking affected rows. Choose for your design and test using the production database engine.",
    "فاضل مكان واحد واتنين بيحجزوا. حل تعليمي: جوّه Transaction اقفل سجل الورشة، افحص المتاح، نقصه، وسجّل الحجز. كل مسارات تعديل السعة لازم تلتزم بنفس التنسيق. بديل ممكن: تحديث شرطي ذري ينقص المتاح فقط لو أكبر من صفر، وتفحص عدد الصفوف المتأثرة. اختار حسب التصميم واختبر على نفس محرك قاعدة بيانات الإنتاج."
  ],
  [
    "Review cancellation too: can it return the same seat twice? Avoid slow external calls inside a lock without a good reason; they make other requests wait longer.",
    "راجع حالات الإلغاء كمان: هل ممكن يرجّع المكان مرتين؟ ماتحطّش اتصال خارجي بطيء جوّه القفل من غير سبب؛ ده بيطوّل الانتظار على الطلبات التانية."
  ],
  [
    "How would you test that the last seat cannot be sold to two people?",
    "إزاي تختبر إن آخر مكان مش هيتباع لاتنين؟"
  ],
  [
    "Send genuinely concurrent attempts using test data. Verify that only one succeeds and the final database state is consistent. Two sequential requests do not test a race condition. Also check repeated cancellation.",
    "ابعت محاولتين متزامنتين فعلًا ببيانات اختبار، واتأكد إن واحدة بس نجحت وإن الداتا النهائية متسقة. تشغيل طلبين وراء بعض مش اختبار Race condition. راجع كمان مسار الإلغاء المتكرر."
  ],
  [
    "I can identify the invariant that must hold under concurrent requests.",
    "أقدر أحدد القاعدة اللي لازم تفضل صحيحة حتى مع طلبات متزامنة."
  ],
  [
    "Reviewed: I can identify the invariant that must hold under concurrent requests.",
    "راجعت المحور: أقدر أحدد القاعدة اللي لازم تفضل صحيحة حتى مع طلبات متزامنة."
  ],
  [
    "Direct link: Protect your rules in the database",
    "رابط مباشر: احمي قواعدك جوّه الداتا"
  ],
  [
    "Signed in does not mean allowed",
    "مش كل اللي دخل، مسموح له"
  ],
  [
    "Data & security",
    "الداتا والأمان"
  ],
  [
    "Authentication tells you who a user is. Authorization determines what they can do to a particular resource.",
    "تسجيل الدخول بيقول لنا مين المستخدم. الصلاحيات بتحدد يقدر يعمل إيه وعلى أنهي مورد."
  ],
  [
    "A valid token is not permission to read any booking. Check access to the requested resource for every action: viewing, updating, cancelling, and exporting. Deny access unless explicitly allowed, and grant only the necessary permissions. Hiding a cancel button is not protection; the server must enforce the decision.",
    "وجود Token سليم مش تصريح لقراءة أي حجز. افحص صلاحية المستخدم على المورد المطلوب في كل عملية: عرض، تعديل، إلغاء، وتصدير. ابدأ بمنع الوصول إلا لما يبقى مسموح بوضوح، وادي أقل صلاحيات لازمة. إخفاء زر الإلغاء في الواجهة مش حماية؛ القرار لازم يتنفّذ في السيرفر."
  ],
  [
    "A user owns booking 41. They change the URL to 42 and see someone else's booking. Authentication worked; resource ownership checks did not. Use a policy or another centralized authorization mechanism that accounts for ownership, role, and booking state.",
    "مستخدم عنده حجز رقم 41، غيّر الرقم في الرابط لـ42 وظهر له حجز شخص تاني. الطلب مرّ من تسجيل الدخول، لكن فحص ملكية المورد ناقص. استخدم Policy أو آلية تفويض مركزية تراعي المالك ودور المستخدم وحالة الحجز."
  ],
  [
    "Do not treat a user_id supplied by the client as proof of identity. Test different users, membership states, and roles rather than only an admin account.",
    "خلي بالك من user_id اللي جاي من العميل. ماينفعش تعتبره دليل هوية. اختبر مستخدمين مختلفين، وحالات العضوية والأدوار، بدل اختبار حساب Admin بس."
  ],
  [
    "Write two failure cases for an endpoint that displays a user's booking.",
    "اكتب حالتين فشل لاختبار عرض حجز مستخدم."
  ],
  [
    "A signed-out visitor cannot see the booking, and a signed-in user cannot see someone else's booking. Define whether the second case returns 403 or 404 to conceal the resource's existence. Either way, its contents must not leak.",
    "زائر من غير تسجيل دخول مايشوفش الحجز، ومستخدم مسجّل مايشوفش حجز غيره. حدّد في عقد الـAPI هل الحالة التانية بترجع 403 أو 404 لإخفاء وجود المورد؛ المهم مايتسرّبش محتواه."
  ],
  [
    "I can distinguish identity verification from resource authorization.",
    "أقدر أفرّق بين إثبات الهوية والتصريح باستخدام مورد بعينه."
  ],
  [
    "Reviewed: I can distinguish identity verification from resource authorization.",
    "راجعت المحور: أقدر أفرّق بين إثبات الهوية والتصريح باستخدام مورد بعينه."
  ],
  [
    "Direct link: Signed in does not mean allowed",
    "رابط مباشر: مش كل اللي دخل، مسموح له"
  ],
  [
    "Design for failure and retries",
    "صمّم للفشل وإعادة المحاولة"
  ],
  [
    "Quality & operations",
    "التشغيل والجودة"
  ],
  [
    "Moving work to a queue changes when it runs. You still need to reason about duplication, ordering, and recovery.",
    "نقل الشغل للـQueue بيغيّر توقيت التنفيذ. لسه محتاج تفكر في التكرار والترتيب والتعافي من الفشل."
  ],
  [
    "Emails and reports are examples of work that can run in the background. Set attempt limits, timeouts, retry delays, and a way to detect permanent failure. A job may run again, so make its effects safe to repeat where possible. In Laravel, dispatching after commit prevents workers from acting on data that has not yet been committed.",
    "إرسال الإيميلات وتوليد التقارير أمثلة لشغل ممكن يتنفّذ في الخلفية. حدّد عدد المحاولات، والـTimeout، والفاصل بين المحاولات، وإزاي تعرف إن الـJob فشلت نهائيًا. الـJob ممكن تتنفّذ تاني؛ خلّي أثرها قابل للتكرار بأمان قدر الإمكان. في Laravel، dispatch بعد الـCommit يمنع الـWorker من التعامل مع داتا لسه مااتثبتتش."
  ],
  [
    "The booking is confirmed but the confirmation email fails. A delayed email should not automatically cancel the booking. Treat the notification as a separate, reviewable operation. If you need stronger protection against losing the event between committing the booking and dispatching the job, study the transactional outbox pattern. afterCommit alone does not close that gap.",
    "الحجز اتأكد وإيميل التأكيد فشل. مش منطقي تلغي الحجز لمجرد إن الإيميل متأخر. سجّل الحجز واتعامل مع الإشعار كعملية منفصلة قابلة للمراجعة. ولو محتاج ضمان أقوى إن حدث الإرسال مايضيعش بين تثبيت الحجز وإرسال الـJob، ادرس Transactional outbox؛ afterCommit لوحدها مش بتقفل الفجوة دي."
  ],
  [
    "If an external service performs an operation but its response is lost, blindly retrying can repeat the effect. Use provider-supported idempotency keys or reconcile the operation's state before retrying.",
    "لو خدمة خارجية نفّذت العملية لكن ردّها ضاع، إعادة الطلب عمياني ممكن تكرّر الأثر. استخدم مفاتيح منع التكرار اللي بتدعمها الخدمة، أو راجع حالة العملية قبل قرار الإعادة."
  ],
  [
    "A job writes a notification to your database. How do you stop it creating the same notification twice?",
    "Job بتعمل إشعار في الداتا. إزاي تمنع إنشاء نفس الإشعار مرتين؟"
  ],
  [
    "Give the event and recipient a stable identity, and protect that pair with an appropriate database constraint. Repeated execution should safely reuse the recorded result. Test running it twice. A temporary lock alone is not a permanent record of what happened.",
    "عرّف هوية ثابتة للحدث والمستقبل، وامنع تكرار الزوج بقيد مناسب في الداتا. خلي التنفيذ المتكرر يلاقي النتيجة الموجودة ويتعامل معاها بأمان، واختبر التنفيذ مرتين. القفل المؤقت لوحده مش سجل دائم للي حصل."
  ],
  [
    "I can explain what happens when a job fails or runs twice.",
    "أقدر أشرح إيه اللي يحصل لو المهمة فشلت أو اتكررت."
  ],
  [
    "Reviewed: I can explain what happens when a job fails or runs twice.",
    "راجعت المحور: أقدر أشرح إيه اللي يحصل لو المهمة فشلت أو اتكررت."
  ],
  [
    "Direct link: Design for failure and retries",
    "رابط مباشر: صمّم للفشل وإعادة المحاولة"
  ],
  [
    "Measure before you scale",
    "قيس قبل ما تكبّر السيستم"
  ],
  [
    "Quality & operations",
    "التشغيل والجودة"
  ],
  [
    "A bigger server is not the automatic answer to slowness. First find where the time goes.",
    "السيرفر الأكبر مش إجابة تلقائية للبطء. شوف الوقت بيتصرف فين الأول."
  ],
  [
    "Loading the user with a separate query for every booking in a list makes query count grow with the list: a form of N+1. Eager loading can fetch required relationships together, but choose fields and page sizes carefully to avoid loading unnecessary data. Inspect query plans and measurements before adding indexes or caching.",
    "لو بتعرض قائمة حجوزات، وبتجيب المستخدم باستعلام منفصل لكل صف، عدد الاستعلامات هيزيد مع حجم القائمة؛ دي صورة من N+1. الـEager loading ممكن يجمع تحميل العلاقات المطلوبة، لكن اختار الحقول والصفحات المناسبة عشان ماتحمّلش داتا مالهاش لزوم. استخدم خطة تنفيذ الاستعلام وقياسات فعلية قبل إضافة Index أو Cache."
  ],
  [
    "A workshop description can be cached, but confirming the last seat must use the source of truth and your concurrency mechanism. When is the cache invalidated? How stale may the information become? Does the cache key isolate users when the result is private?",
    "صفحة الورشة ممكن تعرض وصفًا متخزنًا في Cache، لكن قرار تأكيد آخر مكان لازم يرجع لمصدر الحقيقة وآلية التزامن. فكّر: إمتى الكاش يبطل؟ ومسموح المعلومة تتأخر قد إيه؟ وهل المفتاح بيعزل داتا كل مستخدم لو النتيجة خاصة بيه؟"
  ],
  [
    "Ask AI for a performance hypothesis and a measurement method. Compare query count and response time for the same scenario before and after the change, rather than accepting “the code is faster.”",
    "اطلب من الـAI فرضية للبطء وطريقة لقياسها. قارن عدد الاستعلامات وزمن الاستجابة على نفس السيناريو قبل التعديل وبعده، بدل ما تكتفي بجملة: الكود أسرع."
  ],
  [
    "Does caching the available-seat count for an hour solve overbooking?",
    "إضافة Cache لمدة ساعة لعدد الأماكن المتاحة تحل مشكلة الحجز الزائد؟"
  ],
  [
    "No. The cache may show an old count and does not protect writes. You can use it for display with clear expectations, but the booking decision must atomically verify the authoritative data.",
    "لأ. الكاش ممكن يعرض رقم قديم، ومش بديل عن حماية الكتابة. ممكن تستخدمه للعرض بتوقعات واضحة، لكن قرار الحجز لازم يتحقق بشكل ذري من الداتا الأساسية."
  ],
  [
    "I can justify an optimization with measurements and explain the cost of stale data.",
    "أقدر أختار تحسين مبني على قياس وأشرح تكلفة المعلومة القديمة."
  ],
  [
    "Reviewed: I can justify an optimization with measurements and explain the cost of stale data.",
    "راجعت المحور: أقدر أختار تحسين مبني على قياس وأشرح تكلفة المعلومة القديمة."
  ],
  [
    "Direct link: Measure before you scale",
    "رابط مباشر: قيس قبل ما تكبّر السيستم"
  ],
  [
    "Know when it works—and when it stops",
    "اعرف إنه شغّال… واعرف لما يبطل"
  ],
  [
    "Quality & operations",
    "التشغيل والجودة"
  ],
  [
    "A successful request on your machine is a start. Quality needs evidence before release and useful signals after it.",
    "نجاح الطلب على جهازك بداية. الجودة معناها دليل قبل النشر، وإشارات مفهومة بعده."
  ],
  [
    "Derive tests from product rules: successful booking, denied access, full capacity, and duplicate attempts. Test small logic with unit tests and request/database behavior with integration tests. In production, logs record events, metrics reveal numerical trends, and traces connect parts of a request's journey. Use a request ID for correlation without logging secrets or unnecessary personal data.",
    "ابدأ الاختبارات من قواعد المنتج: نجاح الحجز، رفض غير المصرّح له، امتلاء الورشة، والتكرار. اختبر منطقًا صغيرًا باختبار وحدة، واختبر تكامل الطلب والداتا باختبار تكامل. في التشغيل، الـLogs بتسجّل أحداثًا، والـMetrics بتوضح اتجاهات وأرقامًا، والـTraces بتوصل أجزاء رحلة الطلب. استخدم Request ID للربط، من غير تسجيل أسرار أو بيانات مش محتاجها."
  ],
  [
    "Booking errors increase after a release. You need the application version, start time, and error type, and a way to connect a failed request to a slow query or dependency. Plan rollback before deployment and check database compatibility with the previous version. Rolling back code does not automatically restore data.",
    "بعد نشر تعديل، نسبة أخطاء الحجز زادت. محتاج تعرف إصدار التطبيق، وقت البداية، ونوع الخطأ، وتربط طلبًا فاشلًا بالاستعلام أو الخدمة المتأخرة. قبل النشر حضّر خطة رجوع، وراجع توافق تغييرات قاعدة البيانات مع الإصدار السابق. الرجوع للكود مش بيرجع الداتا تلقائيًا."
  ],
  [
    "If every test only checks a successful response, add assertions for database effects and failure cases. If AI proposes deleting a used column, review migration and compatibility plans before applying it.",
    "لو كل الاختبارات بتقول إن الـResponse ناجح بس، لسه ناقص تحقق من الأثر في الداتا وحالات الفشل. ولو الـAI اقترح حذف عمود مستخدم، راجع خطة نقل البيانات والتوافق قبل التطبيق."
  ],
  [
    "What evidence would you collect when a user says booking sometimes hangs?",
    "إيه الدليل اللي تجمعه لما المستخدم يقول: الحجز ساعات بيعلق؟"
  ],
  [
    "The incident time and request ID if available; response time and error rate; related events; and database/external-service timings. Find a reproducible scenario. Averages can hide slow requests: inspect latency distribution, such as p95, alongside the sample size and time window.",
    "وقت المشكلة ومعرّف الطلب إن وجد، زمن الاستجابة ونسبة الأخطاء، أحداث مرتبطة بالطلب، وزمن الاستعلامات والخدمات الخارجية. جرّب سيناريو يعيد المشكلة. المتوسط لوحده ممكن يخفي طلبات بطيئة؛ بص على توزيع الأزمنة، زي p95، مع حجم العينة والفترة."
  ],
  [
    "I can verify behavior with tests and investigate a production failure.",
    "أقدر أثبت السلوك باختبار وأتتبّع مشكلة بعد النشر."
  ],
  [
    "Reviewed: I can verify behavior with tests and investigate a production failure.",
    "راجعت المحور: أقدر أثبت السلوك باختبار وأتتبّع مشكلة بعد النشر."
  ],
  [
    "Direct link: Know when it works—and when it stops",
    "رابط مباشر: اعرف إنه شغّال… واعرف لما يبطل"
  ],
  [
    "Let AI assist; own the decision",
    "خلّي الـAI يساعدك… وإنت راجع القرار"
  ],
  [
    "Working with AI",
    "التعامل مع AI"
  ],
  [
    "Even when a tool writes most of the implementation, you need to explain it, question its assumptions, and verify its behavior.",
    "حتى لو الأداة كتبت أغلب التنفيذ، لازم تعرف تشرح الكود وتراجع افتراضاته وتتحقق من نتيجته."
  ],
  [
    "Work in small cycles: clarify the task, request a plan and assumptions, review them, implement a limited change, then inspect the diff and run tests. Supply the framework version, relevant files, and project rules. The tool's explanation is not proof of correctness. Consult version-appropriate documentation and run the scenario yourself. This is a suggested workflow, not a promise about any particular tool.",
    "اشتغل بدورة صغيرة: وضّح المطلوب، اطلب خطة وافتراضات، راجعها، نفّذ جزءًا محدودًا، وبعدها افحص الفرق وشغّل الاختبارات. ادّي الأداة إصدار الـFramework والملفات ذات الصلة وقواعد المشروع. ماتعتبرش شرحها لنفسها دليلًا على الصحة؛ افتح التوثيق المناسب للإصدار، وشغّل الحالة بنفسك. دي طريقة شغل مقترحة هنا، مش وعد إن أداة بعينها هتتصرف دايمًا صح."
  ],
  [
    "AI generates a booking transaction and a passing test. Is that test actually concurrent? Was access checked? What happens if cancellation runs twice? If you cannot answer, reduce the change and understand that part first. Use suitable synthetic examples rather than including project secrets or users' data in your prompt.",
    "الأداة كتبت حجزًا فيه Transaction واختبارًا أخضر. اسأل: الاختبار متزامن فعلًا؟ الصلاحيات اتفحصت؟ إلغاء الحجز مرتين بيعمل إيه؟ لو مش عارف تجاوب، صغّر التغيير وافهم الجزء ده قبل ما تكمّل. ما تبعتش أسرار المشروع أو بيانات المستخدمين ضمن المثال؛ اعمل بيانات تدريبية مناسبة."
  ],
  [
    "Also inspect new dependencies, migrations, swallowed errors, and tests changed just to pass. Ask for the choices and alternatives, then make the final decision based on your requirements and evidence.",
    "راجع كمان الـDependencies اللي اتضافت، والـMigrations، وأي كود بيتجاهل خطأ أو بيغيّر اختبار عشان يعدّي. اطلب تفسير الاختيارات والبدائل، وخلّي الحكم النهائي مربوطًا بمتطلباتك وبالدليل."
  ],
  [
    "Write an AI review request for the booking feature that is more specific than “review the code.”",
    "اكتب طلب للـAI لمراجعة ميزة الحجز، من غير ما تقول له بس: راجع الكود."
  ],
  [
    "Review creation and cancellation in the specified files. Rules: capacity cannot exceed 20, and each user has one active booking. Look for authorization, duplication, and concurrency failures. For each finding, identify its location, a reproduction scenario, and a test that exposes it. Separate confirmed issues from assumptions and ask for missing context before editing.",
    "راجع مسار إنشاء وإلغاء الحجز في الملفات المحددة. القواعد: السعة لا تتجاوز 20، وكل مستخدم له حجز فعّال واحد. ابحث عن فشل الصلاحيات والتكرار والتزامن. لكل مشكلة، اذكر مكانها وسيناريو يعيدها واختبارًا يكشفها. افصل المؤكد عن الافتراضات، واسأل عن الناقص قبل التعديل."
  ],
  [
    "I can verify a tool's proposal independently and own the merge decision.",
    "أقدر أراجع اقتراح الأداة بدليل مستقل وأتحمل قرار دمجه."
  ],
  [
    "Reviewed: I can verify a tool's proposal independently and own the merge decision.",
    "راجعت المحور: أقدر أراجع اقتراح الأداة بدليل مستقل وأتحمل قرار دمجه."
  ],
  [
    "Direct link: Let AI assist; own the decision",
    "رابط مباشر: خلّي الـAI يساعدك… وإنت راجع القرار"
  ],
  [
    "Published: February 14, 2026",
    "تاريخ النشر: 14 فبراير 2026"
  ],
  [
    "Reading time: 30–40 minutes",
    "مدة القراءة: 30–40 دقيقة"
  ],
  [
    "If you are a",
    "لو أنت"
  ],
  [
    "and want to build systems that can",
    "وعايز تبني Systems تستحمل"
  ],
  [
    "and operate in",
    "وتعيش في"
  ],
  [
    "reliably, this is a practical reference. Explanations retain the core",
    "بثبات، فالمحاضرة دي معمولة كمرجع عملي. الشرح بالعربي، والمصطلحات الأساسية بالـ"
  ],
  [
    "terminology used in engineering teams and technical interviews.",
    "عشان تفضل مرتبطة بسوق الشغل والمقابلات التقنية."
  ],
  [
    "Discuss a backend project",
    "احجز استشارة Backend"
  ],
  [
    "The goal:",
    "الهدف من المحاضرة:"
  ],
  [
    "Shift your thinking from",
    "تحويل طريقة تفكيرك من"
  ],
  [
    "to",
    "إلى"
  ],
  [
    ": planning, trade-offs, and production operation.",
    ": تخطيط + Trade-offs + تشغيل في الإنتاج (Production Ready)."
  ],
  [
    "0) Lecture map",
    "0) خريطة المحاضرة | Lecture Map"
  ],
  [
    "1) What is system design?",
    "1) يعني إيه System Design أساسًا؟"
  ],
  [
    "is the art of choosing",
    "هو فن اختيار"
  ],
  [
    "and",
    "و"
  ],
  [
    "so that a system meets",
    "بطريقة تخلي النظام يحقق"
  ],
  [
    "within real constraints:",
    "تحت قيود حقيقية:"
  ],
  [
    ",",
    "،"
  ],
  [
    ", and a limited team. Choose tools to reduce risk and deliver",
    "، وفريق محدود. أنت مش بتختار Tools عشان trendy… أنت بتختار قرارات تقلل المخاطر وتضمن"
  ],
  [
    "2) Requirements: before the first diagram",
    "2) Requirements: أول خطوة قبل أي Diagram"
  ],
  [
    "What does the system",
    "إيه اللي النظام"
  ],
  [
    "need to",
    "لازم"
  ],
  [
    "do? For example: a user creates an order, pays, and tracks delivery. Write clear use cases.",
    "يعمله؟ مثال: “User creates order, pays, tracks delivery”. اكتبها كبنود واضحة (use-cases)."
  ],
  [
    "These are important engineering decisions. Express them as measurable targets or limits where possible:",
    "دي اللي بتفرق Junior عن Senior. لازم تتحول لأرقام/حدود قدر الإمكان:"
  ],
  [
    "p95 < 200ms (example)",
    "p95 < 200ms (مثال)"
  ],
  [
    "99.9% or 99.99%?",
    "99.9% ولا 99.99%؟"
  ],
  [
    "QPS / RPS at peak",
    "QPS / RPS في الذروة"
  ],
  [
    "What data-loss guarantees are needed?",
    "هل البيانات لازم متضيعش؟"
  ],
  [
    "A useful rule:",
    "قاعدة ذهبية:"
  ],
  [
    "Unclear non-functional requirements can produce a design that looks good on paper but fails in production.",
    "لو ما كتبتش NFRs بوضوح، هتصمم نظام “كويس على الورق” ويفشل في الإنتاج."
  ],
  [
    "2.3 Success metrics: SLOs and SLIs",
    "2.3 Success Metrics (SLO/SLI) بشكل بسيط"
  ],
  [
    "An actual measurement (p95 latency, error rate)",
    "قياس فعلي (p95 latency, error rate)"
  ],
  [
    "The target (for example, error rate < 0.1%)",
    "الهدف (مثلاً error rate < 0.1%)"
  ],
  [
    "A business commitment to a customer, potentially with higher costs",
    "التزام تجاري مع العميل (ممكن يكون أعلى كلفة)"
  ],
  [
    "3) Capacity planning: quick estimates",
    "3) Capacity Planning: أرقام بسرعة (بدون فلسفة)"
  ],
  [
    "Before proposing microservices or sharding, understand expected scale:",
    "قبل ما تقول “هنعمل Microservices / Sharding”، لازم تفهم الحجم المتوقع:"
  ],
  [
    "DAU/MAU, requests per user, peak factor",
    "DAU/MAU، requests per user، peak factor"
  ],
  [
    "2× in a year? 10×?",
    "2× في سنة؟ 10×؟"
  ],
  [
    "4) HTTP and API design essentials",
    "4) HTTP & API Design (أساسيات لا غنى عنها)"
  ],
  [
    "200/201/204, 400, 401, 403, 404, 409, 429, 500",
    "200/201/204، 400، 401، 403، 404، 409، 429، 500"
  ],
  [
    "GET/PUT/DELETE have idempotent semantics; POST does not by default",
    "GET/PUT/DELETE غالبًا Idempotent، لكن POST غالبًا لا"
  ],
  [
    "Not every error should be retried",
    "مش كل error ينفع تعيد عليه"
  ],
  [
    "/v1 or headers",
    "/v1 أو headers"
  ],
  [
    "Cursor-based pagination can be preferable for large datasets",
    "Cursor-based أفضل من Offset مع الداتا الكبيرة"
  ],
  [
    "Clear request/response schemas",
    "schema واضحة للـ request/response"
  ],
  [
    "Avoid breaking existing clients",
    "ما تكسرش clients"
  ],
  [
    "4.3 Idempotency keys",
    "4.3 Idempotency Keys (مهم جدًا)"
  ],
  [
    "For operations such as payments or order creation, use an",
    "في عمليات حساسة زي الدفع/إنشاء طلب، استخدم"
  ],
  [
    "so an accidentally repeated request does not cause a",
    "عشان لو العميل كرر الطلب بالغلط، ما يحصلش"
  ],
  [
    "Data consistency versus read performance",
    "صحة البيانات مقابل سرعة القراءة"
  ],
  [
    "Consider indexes for frequently filtered columns",
    "Index للأعمدة الأكثر استخدامًا في filters"
  ],
  [
    "Order composite index columns appropriately",
    "Composite indexes بترتيب مناسب"
  ],
  [
    "Avoid unnecessary full scans",
    "تجنب full scans قدر الإمكان"
  ],
  [
    "Use",
    "استخدم"
  ],
  [
    "instead of guessing",
    "بدل التخمين"
  ],
  [
    "Have a retry strategy for deadlock errors",
    "لازم يكون عندك retry strategy للـ deadlock errors"
  ],
  [
    "Inventory, booking, and money systems must address concurrency (",
    "أي نظام فيه inventory/booking/money لازم يتعامل مع السباقات ("
  ],
  [
    "). Use an explicit strategy rather than relying on timing.",
    "). الحل مش “حظ” — الحل Strategy واضحة."
  ],
  [
    "Prevent duplicates at the database level",
    "تمنع duplication على مستوى DB"
  ],
  [
    "Prevent duplicate effects caused by retries",
    "تمنع duplicate writes بسبب retries"
  ],
  [
    "7) Caching fundamentals in depth",
    "7) Caching Fundamentals بعمق"
  ],
  [
    "Caching is an architectural decision, not just adding Redis. Consider:",
    "Caching مش مجرد Redis تحطه وخلاص. ده قرار Architecture يتبني على:"
  ],
  [
    "+ data change frequency + tolerance for",
    "+ معدل تغيّر الداتا + مدى قبول"
  ],
  [
    "7.1 Cache layers",
    "7.1 أنواع Caching حسب المكان"
  ],
  [
    "Buffer pools / query caches, depending on the database",
    "buffer pools / query cache (حسب DB)"
  ],
  [
    "7.2 Common caching patterns",
    "7.2 Caching Patterns المشهورة"
  ],
  [
    "Write cache first → persist asynchronously (faster, with additional risks)",
    "write cache first → persist DB async (أسرع لكن أخطر)"
  ],
  [
    "7.3 Choosing an approach",
    "7.3 إمتى تستخدم إيه؟"
  ],
  [
    "Useful for read-heavy workloads with moderately changing data",
    "مناسب جدًا للـ read-heavy مع data تتغير بمعدل متوسط"
  ],
  [
    "Consider when stale data is costly; still define consistency guarantees",
    "للبيانات الحساسة اللي stale فيها مؤذي"
  ],
  [
    "High throughput with strong durability and replay controls",
    "high throughput مع controls قوية (durability + replay)"
  ],
  [
    "7.4 Cache failure modes",
    "7.4 مشاكل الكاش اللي لازم تكون عارفها"
  ],
  [
    "Plan event-based invalidation or versioned keys",
    "أصعب نقطة → event-based invalidation / versioned keys"
  ],
  [
    "Many keys expire together → database pressure",
    "انتهاء keys معًا → ضغط على DB"
  ],
  [
    "One key receives very high traffic",
    "key واحدة عليها traffic عالي جدًا"
  ],
  [
    "An empty cache after a deployment or restart",
    "بعد deploy/restart cache فاضية"
  ],
  [
    "to reduce simultaneous expiry",
    "لتقليل simultaneous expiration"
  ],
  [
    "Use a consistent namespace:entity:id:version structure",
    "ثابتة: namespace:entity:id:version"
  ],
  [
    "Monitor",
    "راقب"
  ],
  [
    "Database fallback must remain safe, using",
    "fallback للـ DB لازم يبقى safe مع"
  ],
  [
    "Document the invalidation policy for each write",
    "وثّق invalidation policy عند كل write"
  ],
  [
    "Not every task belongs inside a request. Use asynchronous work for long tasks, traffic spikes, or unreliable integrations.",
    "مش كل حاجة ينفع تتعمل “داخل request”. استخدم async لما: المهمة طويلة، أو محتاج تمتص spikes، أو عندك integrations بتقع كتير."
  ],
  [
    "Often at-least-once → consumers must tolerate repeated delivery",
    "غالبًا at-least-once → consumers لازم تكون idempotent"
  ],
  [
    "A dead-letter queue for failed messages",
    "Dead Letter Queue للرسائل اللي بتفشل"
  ],
  [
    "When consumers cannot keep up",
    "لما consumer مش لاحق"
  ],
  [
    "8.2 The outbox pattern",
    "8.2 Outbox Pattern (مهم جدًا)"
  ],
  [
    "When updating a database and publishing an event, one operation can succeed while the other fails. Record the event in an outbox table within the same transaction, then let a worker publish it.",
    "لو بتكتب في DB وبتبعت event/message، تجنّب إن DB تنجح والـ publish يفشل (أو العكس). الحل: تكتب الحدث في جدول Outbox داخل نفس transaction، وبعدين worker ينشره."
  ],
  [
    "Every dependency needs an explicit timeout",
    "كل dependency لازم لها timeout واضح"
  ],
  [
    "Missing timeouts can cause thread starvation and cascading failures",
    "بدون timeout = thread starvation + cascading failures"
  ],
  [
    "Bounded retries +",
    "retries محدودة +"
  ],
  [
    "Retry only appropriate operations with safe repetition semantics",
    "أعد المحاولة فقط في الحالات المناسبة (idempotent operations)"
  ],
  [
    "Most 4xx errors are not fixed by simply retrying",
    "4xx غالبًا مش محتاجة retry"
  ],
  [
    "Stops a failing dependency from exhausting the whole system. States: open, closed, and half-open.",
    "يحميك من إن dependency واقعة تسحب النظام كله معاها. (Open/Closed/Half-open)"
  ],
  [
    "Disable a non-essential feature rather than fail the whole system",
    "اقفل feature غير أساسية بدل ما النظام يقع كله"
  ],
  [
    "Serve stale cache where acceptable",
    "serve stale cache لو ينفع"
  ],
  [
    "Return a useful partial response where the contract allows",
    "partial responses بدل 500"
  ],
  [
    "agreed in advance",
    "متفق عليهم"
  ],
  [
    "Clear runbooks for on-call engineers",
    "Runbooks واضحة للـ on-call"
  ],
  [
    "The request journey across services",
    "request journey عبر services"
  ],
  [
    "Focus on user impact, not only CPU spikes",
    "على user impact (مش CPU spikes بس)"
  ],
  [
    "11) A backend API security baseline",
    "11) Security Baseline لأي Backend API"
  ],
  [
    "Check every input at the boundary",
    "على كل input عند boundary"
  ],
  [
    "JWT / sessions / OAuth2, depending on the use case",
    "JWT / sessions / OAuth2 (حسب الحالة)"
  ],
  [
    "Keep secrets out of source control and plan rotation",
    "لا تضع secrets في source code + rotation"
  ],
  [
    "Protect against abuse and brute force",
    "حماية من abuse و brute force"
  ],
  [
    "For sensitive operations",
    "للعمليات الحساسة"
  ],
  [
    "12) Scaling: vertical or horizontal?",
    "12) Scaling Strategy: رأسي ولا أفقي؟"
  ],
  [
    "Before considering",
    "قبل ما تفكر في"
  ],
  [
    ", first improve:",
    "، اتأكد إنك صححت:"
  ],
  [
    "+ bottlenecks. Improve efficiency before adding scale.",
    "+ bottlenecks. Scaling الحقيقي ييجي بعد efficiency."
  ],
  [
    "Quick to apply but limited",
    "حل سريع لكنه محدود"
  ],
  [
    "Separate read workloads from writes",
    "للفصل بين reads و writes"
  ],
  [
    "When one database is insufficient; adds complexity",
    "لما single DB مش مكفي (يزود التعقيد)"
  ],
  [
    "Queue controls or rate limiting at peak",
    "queue-based أو rate limiting وقت الذروة"
  ],
  [
    "13.1 Safe database migrations",
    "13.1 Database Migrations بدون كسر الإنتاج"
  ],
  [
    "Avoid long locks, especially on large tables",
    "avoid long locks (خاصة على جداول كبيرة)"
  ],
  [
    "Use feature flags for gradual rollout",
    "feature flags للتدرّج"
  ],
  [
    "Rollback needs data compatibility, not just an older code version",
    "Rollback مش بس “ارجع كود” — لازم البيانات تكون قابلة للتعايش"
  ],
  [
    "Use blue/green or canary deployment to reduce rollout risk",
    "Blue/Green أو Canary لتقليل المخاطر"
  ],
  [
    "14) System design review checklist",
    "14) Backend System Design Checklist (قبل ما تقول Done)"
  ],
  [
    "Have you defined",
    "هل عندك"
  ],
  [
    "clearly (latency, availability, throughput)?",
    "واضحة (latency, availability, throughput)؟"
  ],
  [
    "for QPS, storage, and growth?",
    "(QPS/storage/growth)؟"
  ],
  [
    "Are your",
    "هل"
  ],
  [
    "clear, including versioning, pagination, and idempotency?",
    "واضحة + versioning + pagination + idempotency؟"
  ],
  [
    "Is the data model informed by queries, indexes, and EXPLAIN?",
    "هل data model مبني على queries + indexes + EXPLAIN؟"
  ],
  [
    "Is the caching strategy documented, including invalidation and TTL?",
    "هل caching strategy موثقة (pattern + invalidation + TTL)؟"
  ],
  [
    "Have you planned for timeouts, retries, and dependency failures?",
    "هل failure modes متوقعة (timeouts/retries/circuit breaker)؟"
  ],
  [
    "Are logs, metrics, traces, and alerts in place?",
    "هل عندك observability (logs/metrics/tracing/alerts)؟"
  ],
  [
    "Does the security baseline cover authorization, secrets, rate limits, and auditing?",
    "هل security baseline متحقق (authz/secrets/rate limit/audit)؟"
  ],
  [
    "Does deployment include gradual rollout and rollback?",
    "هل deployment plan فيه gradual rollout + rollback؟"
  ],
  [
    "Putting it into practice",
    "الخلاصة"
  ],
  [
    "Backend engineering means managing complexity through clear decisions, beyond knowing a framework. Treat",
    "الـ Backend القوي مش اللي يعرف framework بس، لكن اللي يقدر يدير complexity بقرارات بسيطة وواضحة. اعتبر"
  ],
  [
    "as core parts of a feature rather than afterthoughts.",
    "أجزاء أساسية من أي Feature، مش إضافات لاحقة."
  ],
  [
    "Read more articles",
    "اقرأ مقالات أكثر"
  ],
  [
    "Discuss a backend project",
    "تواصل لمشروع Backend"
  ],
  [
    "Legal consultation platform backend supporting request lifecycles, lawyer/admin workflows, notifications, and service operations.",
    "باك إند لمنصة استشارات قانونية، بيدير مراحل الطلب وشغل المحامين والإدارة والإشعارات والخدمات."
  ],
  [
    "Legal service requests need strict role permissions, clear status progression, and reliable admin visibility.",
    "طلبات الخدمات القانونية محتاجة صلاحيات دقيقة ومراحل حالة واضحة ومتابعة موثوقة من الإدارة."
  ],
  [
    "Designed Laravel APIs, request lifecycle logic, admin operations, and role/permission boundaries for product workflows.",
    "صمّمت Laravel APIs ومنطق مراحل الطلب وعمليات الإدارة وحدود الأدوار والصلاحيات."
  ],
  [
    "A production-ready backend architecture that keeps legal request operations trackable, auditable, and easy to manage.",
    "باك إند جاهز للتشغيل، بيخلّي الطلبات القانونية سهلة المتابعة والمراجعة والإدارة."
  ],
  [
    "Consultation requests",
    "طلبات الاستشارات"
  ],
  [
    "Request lifecycle",
    "مراحل الطلب"
  ],
  [
    "Role-based access",
    "صلاحيات حسب الدور"
  ],
  [
    "Notifications",
    "الإشعارات"
  ],
  [
    "Admin workflow",
    "شغل الإدارة"
  ],
  [
    "Faster service handling",
    "معالجة أسرع للخدمات"
  ],
  [
    "Operational visibility",
    "وضوح في التشغيل"
  ],
  [
    "Reliable client workflows",
    "خطوات موثوقة للعميل"
  ],
  [
    "User backend for the Personal Shipper project, delivered with Technical Package in Saudi Arabia.",
    "باك إند تطبيق المستخدم لمشروع Personal Shipper، ضمن شغلي مع تكنيكال باكدج في السعودية."
  ],
  [
    "Support the user-facing side of the Personal Shipper application.",
    "توفير أساس برمجي لتطبيق المستخدم في Personal Shipper."
  ],
  [
    "Backend development as part of my work with Technical Package.",
    "تطوير الباك إند ضمن شغلي مع تكنيكال باكدج."
  ],
  [
    "A dedicated backend repository for the user application.",
    "مستودع باك إند مخصص لتطبيق المستخدم."
  ],
  [
    "User backend",
    "باك إند المستخدم"
  ],
  [
    "Part of the Technical Package project portfolio",
    "جزء من مشاريع شركة تكنيكال باكدج"
  ],
  [
    "User backend for the Personal Shipper project, delivered with Technical Package in Saudi Arabia.",
    "باك إند تطبيق المستخدم لمشروع Personal Shipper، ضمن شغلي مع تكنيكال باكدج في السعودية."
  ],
  [
    "Backend project for Albhkaly Family Tree, delivered with Technical Package in Saudi Arabia.",
    "باك إند مشروع شجرة عائلة البهكلي، ضمن شغلي مع تكنيكال باكدج في السعودية."
  ],
  [
    "Provide a backend foundation for a family-tree application.",
    "توفير أساس باك إند لتطبيق شجرة العائلة."
  ],
  [
    "Backend development as part of my work with Technical Package.",
    "تطوير الباك إند ضمن شغلي مع تكنيكال باكدج."
  ],
  [
    "A dedicated backend project supporting the Albhkaly application.",
    "مشروع باك إند مخصص لدعم تطبيق عائلة البهكلي."
  ],
  [
    "Family tree application",
    "تطبيق شجرة العائلة"
  ],
  [
    "Part of the Technical Package project portfolio",
    "جزء من مشاريع شركة تكنيكال باكدج"
  ],
  [
    "Backend project for Albhkaly Family Tree, delivered with Technical Package in Saudi Arabia.",
    "باك إند مشروع شجرة عائلة البهكلي، ضمن شغلي مع تكنيكال باكدج في السعودية."
  ],
  [
    "Laravel application backend for Afaq, part of my work with Technical Package in Saudi Arabia.",
    "باك إند Laravel لمشروع آفاق، ضمن شغلي مع تكنيكال باكدج في السعودية."
  ],
  [
    "Provide a structured application backend for the Afaq project.",
    "توفير باك إند منظّم لمشروع آفاق."
  ],
  [
    "Backend development as part of my work with Technical Package.",
    "تطوير الباك إند ضمن شغلي مع تكنيكال باكدج."
  ],
  [
    "A Laravel 10 codebase with Sanctum and a modular application structure.",
    "مشروع Laravel 10 مع Sanctum وبنية تطبيق مقسّمة لمكوّنات."
  ],
  [
    "Laravel application",
    "تطبيق Laravel"
  ],
  [
    "Sanctum authentication",
    "تسجيل الدخول باستخدام Sanctum"
  ],
  [
    "Part of the Technical Package project portfolio",
    "جزء من مشاريع شركة تكنيكال باكدج"
  ],
  [
    "Laravel application backend for Afaq, part of my work with Technical Package in Saudi Arabia.",
    "باك إند Laravel لمشروع آفاق، ضمن شغلي مع تكنيكال باكدج في السعودية."
  ],
  [
    "Commerce and service APIs covering products, orders, quotations, shipping, payments, and chat.",
    "واجهات تجارة وخدمات للمنتجات والطلبات وعروض الأسعار والشحن والدفع والمحادثات."
  ],
  [
    "Connect product browsing, service requests, and order operations through application APIs.",
    "ربط تصفّح المنتجات وطلبات الخدمات وإدارة الطلبات عن طريق الـAPIs."
  ],
  [
    "Backend development as part of my work with Technical Package.",
    "تطوير الباك إند ضمن شغلي مع تكنيكال باكدج."
  ],
  [
    "Laravel API modules for authentication, commerce, service workflows, shipments, payment callbacks, and conversations.",
    "مكوّنات Laravel للمصادقة والتجارة والخدمات والشحن واستجابات الدفع والمحادثات."
  ],
  [
    "Products and carts",
    "المنتجات وسلة الشراء"
  ],
  [
    "Orders and quotations",
    "الطلبات وعروض الأسعار"
  ],
  [
    "Shipping and shipments",
    "الشحن والشحنات"
  ],
  [
    "Payment callbacks",
    "استجابات الدفع"
  ],
  [
    "Chat and ratings",
    "المحادثات والتقييمات"
  ],
  [
    "Part of the Technical Package project portfolio",
    "جزء من مشاريع شركة تكنيكال باكدج"
  ],
  [
    "Commerce and service APIs covering products, orders, quotations, shipping, payments, and chat.",
    "واجهات تجارة وخدمات للمنتجات والطلبات وعروض الأسعار والشحن والدفع والمحادثات."
  ],
  [
    "Legal consultation platform backend with robust lifecycle and permission handling.",
    "باك إند لاستشارات قانونية بمراحل طلب وصلاحيات واضحة."
  ],
  [
    "Multi-role legal workflows needed strict process control.",
    "شغل قانوني بأدوار متعددة كان محتاج تحكم دقيق في المراحل."
  ],
  [
    "Built Laravel backend APIs, request states, and dashboard operations.",
    "بنيت Laravel APIs وحالات الطلب وعمليات لوحة التحكم."
  ],
  [
    "Delivered structured request lifecycle and admin visibility.",
    "نظّمت مراحل الطلب والمتابعة من الإدارة."
  ],
  [
    "Consultation requests",
    "طلبات الاستشارات"
  ],
  [
    "Role-based access",
    "صلاحيات حسب الدور"
  ],
  [
    "Admin workflow",
    "شغل الإدارة"
  ],
  [
    "Clear request tracking",
    "متابعة واضحة للطلبات"
  ],
  [
    "Faster operations",
    "عمليات أسرع"
  ],
  [
    "Reliable service flow",
    "خدمة بخطوات موثوقة"
  ],
  [
    "Backend for legal service requests and admin moderation at operational scale.",
    "باك إند لطلبات الخدمات القانونية وإشراف الإدارة على التشغيل."
  ],
  [
    "Centralized operations backend for records, users, workflows, and reports.",
    "باك إند مركزي للسجلات والمستخدمين وخطوات الشغل والتقارير."
  ],
  [
    "Internal teams needed one reliable operational dashboard.",
    "الفرق الداخلية كانت محتاجة لوحة تشغيل واحدة تعتمد عليها."
  ],
  [
    "Implemented backend modules and dashboard business logic.",
    "نفّذت أجزاء الباك إند ومنطق الشغل في لوحة التحكم."
  ],
  [
    "Unified backoffice backend with maintainable modules.",
    "وحّدت الإدارة الداخلية في أجزاء سهلة التطوير."
  ],
  [
    "User management",
    "إدارة المستخدمين"
  ],
  [
    "Reporting",
    "التقارير"
  ],
  [
    "Admin operations",
    "عمليات الإدارة"
  ],
  [
    "Faster control",
    "تحكم أسرع"
  ],
  [
    "Cleaner operations",
    "عمليات أوضح"
  ],
  [
    "Higher visibility",
    "متابعة أفضل"
  ],
  [
    "Internal operations dashboard backend for day-to-day business control.",
    "باك إند للعمليات الداخلية والتحكم في الشغل اليومي."
  ],
  [
    "Restaurant backend covering QR menus, branch logic, and dashboard operations.",
    "باك إند مطاعم بيجمع قوائم QR ومنطق الفروع ولوحة التحكم."
  ],
  [
    "Menu, branch, and QR journeys needed one coherent backend.",
    "القوائم والفروع وتجربة QR كانت محتاجة باك إند موحّد."
  ],
  [
    "Developed API logic for menus, branches, and admin controls.",
    "طوّرت منطق APIs للقوائم والفروع وأدوات الإدارة."
  ],
  [
    "Connected customer journey and operations via Laravel backend.",
    "ربطت تجربة العميل بالتشغيل من خلال Laravel."
  ],
  [
    "QR menus",
    "قوائم QR"
  ],
  [
    "Branch logic",
    "منطق الفروع"
  ],
  [
    "Dashboard control",
    "تحكم من اللوحة"
  ],
  [
    "Smoother branch operations",
    "تشغيل أسهل للفروع"
  ],
  [
    "Better customer access",
    "وصول أسهل للعملاء"
  ],
  [
    "Scalable menu flow",
    "قوائم قابلة للنمو"
  ],
  [
    "Restaurant backend linking QR experiences, branches, and admin workflows.",
    "باك إند مطاعم بيربط تجربة QR بالفروع والإدارة."
  ],
  [
    "Digital operations backend for order validation, user actions, and admin control.",
    "باك إند للمنتجات الرقمية والتحقق من الطلبات وإجراءات المستخدمين والإدارة."
  ],
  [
    "Digital product orders needed strict validation and operational tracking.",
    "طلبات المنتجات الرقمية كانت محتاجة تحقق دقيق ومتابعة تشغيل."
  ],
  [
    "Worked on order APIs, validation rules, and dashboard logic.",
    "اشتغلت على APIs الطلبات وقواعد التحقق ومنطق لوحة التحكم."
  ],
  [
    "Structured backend workflows for predictable order operations.",
    "نظّمت خطوات الطلبات بسلوك واضح ومتوقع."
  ],
  [
    "Order flow",
    "مراحل الطلب"
  ],
  [
    "Secure validation",
    "تحقق آمن"
  ],
  [
    "Admin dashboard",
    "لوحة الإدارة"
  ],
  [
    "Traceable order flow",
    "طلبات قابلة للتتبع"
  ],
  [
    "Less manual overhead",
    "شغل يدوي أقل"
  ],
  [
    "Operational confidence",
    "ثقة في التشغيل"
  ],
  [
    "Order and validation backend for digital product operations.",
    "باك إند للطلبات والتحقق في تشغيل المنتجات الرقمية."
  ],
  [
    "Modular business backend with authentication, clean endpoints, and admin actions.",
    "باك إند بأجزاء مستقلة وتسجيل دخول وEndpoints واضحة وأدوات إدارة."
  ],
  [
    "The product needed a modular backend without duplicated logic.",
    "المنتج كان محتاج باك إند مقسّم من غير تكرار للمنطق."
  ],
  [
    "Implemented modular services, auth flows, and endpoint standards.",
    "نفّذت خدمات مستقلة وتسجيل دخول ومعايير للـEndpoints."
  ],
  [
    "Reusable Laravel API modules for web and mobile clients.",
    "أجزاء Laravel APIs قابلة لإعادة الاستخدام للويب والموبايل."
  ],
  [
    "Modular APIs",
    "APIs مستقلة"
  ],
  [
    "Authentication",
    "تسجيل الدخول"
  ],
  [
    "Admin actions",
    "إجراءات الإدارة"
  ],
  [
    "Maintainable modules",
    "أجزاء سهلة الصيانة"
  ],
  [
    "Reusable logic",
    "منطق قابل لإعادة الاستخدام"
  ],
  [
    "Cleaner contracts",
    "عقود أوضح"
  ],
  [
    "Modular backend architecture for business operations and product clients.",
    "تصميم باك إند بأجزاء مستقلة لعمليات الشغل وتطبيقات المنتج."
  ],
  [
    "Commerce backend for catalog, order operations, and mobile-ready APIs.",
    "باك إند تجارة للكتالوج والطلبات وAPIs جاهزة للموبايل."
  ],
  [
    "Commerce operations needed consistent product and order handling.",
    "تشغيل المتجر كان محتاج تعامل متسق مع المنتجات والطلبات."
  ],
  [
    "Built backend modules for catalogs, ordering, and API responses.",
    "بنيت أجزاء الكتالوج والطلب وردود الـAPI."
  ],
  [
    "Structured Laravel commerce backend with predictable flows.",
    "باك إند Laravel للتجارة بمراحل منظّمة وواضحة."
  ],
  [
    "Catalog management",
    "إدارة الكتالوج"
  ],
  [
    "Order logic",
    "منطق الطلبات"
  ],
  [
    "Mobile APIs",
    "APIs الموبايل"
  ],
  [
    "Cleaner catalog flow",
    "كتالوج أوضح"
  ],
  [
    "Reliable checkout operations",
    "إتمام طلبات موثوق"
  ],
  [
    "Mobile-ready backend",
    "باك إند جاهز للموبايل"
  ],
  [
    "Product catalog and order backend designed for commerce reliability.",
    "باك إند للكتالوج والطلبات مصمّم لتجارة موثوقة."
  ],
  [
    "Restaurant product backend for menus, orders, branch operations, and admin dashboards.",
    "باك إند مطاعم للقوائم والطلبات وتشغيل الفروع ولوحات الإدارة."
  ],
  [
    "Restaurant platform needed cohesive menu, order, and branch logic.",
    "منصة المطعم كانت محتاجة منطق مترابط للقوائم والطلبات والفروع."
  ],
  [
    "Implemented API and dashboard backend modules for operations.",
    "نفّذت أجزاء APIs ولوحة تحكم لتشغيل المنتج."
  ],
  [
    "Unified Laravel backend across customer and admin journeys.",
    "وحّدت باك إند Laravel لتجربة العميل والإدارة."
  ],
  [
    "Menu system",
    "نظام القوائم"
  ],
  [
    "Order flow",
    "مراحل الطلب"
  ],
  [
    "Branch operations",
    "تشغيل الفروع"
  ],
  [
    "Organized data flows",
    "داتا منظّمة"
  ],
  [
    "Consistent operations",
    "تشغيل متسق"
  ],
  [
    "Branch-ready scaling",
    "توسّع مناسب للفروع"
  ],
  [
    "Backend system for menus, orders, and branch-level operations.",
    "باك إند للقوائم والطلبات وتشغيل كل فرع."
  ],
  [
    "Content and service platform backend with category, media, and dashboard workflows.",
    "باك إند منصة محتوى وخدمات، بيدير التصنيفات والميديا وخطوات الإدارة."
  ],
  [
    "Content-heavy platforms needed a simpler and structured backend CMS flow.",
    "المحتوى الكبير كان محتاج إدارة أبسط وباك إند CMS منظّم."
  ],
  [
    "Implemented backend structure, category logic, and media-related admin operations.",
    "نفّذت هيكل الباك إند ومنطق التصنيفات وعمليات إدارة الميديا."
  ],
  [
    "Built a Laravel content backend optimized for maintainability and dashboard control.",
    "بنيت Laravel CMS سهل الصيانة والتحكم من اللوحة."
  ],
  [
    "Content management",
    "إدارة المحتوى"
  ],
  [
    "Categories",
    "التصنيفات"
  ],
  [
    "Media handling",
    "إدارة الميديا"
  ],
  [
    "Cleaner content operations",
    "تشغيل محتوى أوضح"
  ],
  [
    "Easier updates",
    "تحديثات أسهل"
  ],
  [
    "Better admin structure",
    "إدارة أنظم"
  ],
  [
    "Content/service backend with dashboard-managed structure and cleaner media workflows.",
    "باك إند محتوى وخدمات، بيتدار من لوحة تحكم بخطوات ميديا أوضح."
  ],
  [
    "Transaction-focused backend with validation, audit records, and dashboard visibility.",
    "باك إند للمعاملات مع تحقق وسجل مراجعة ومتابعة من لوحة التحكم."
  ],
  [
    "Transaction products needed reliable record tracking and validation checks.",
    "منتج المعاملات كان محتاج تسجيل موثوق وقواعد تحقق واضحة."
  ],
  [
    "Implemented transaction backend logic, validation rules, and admin visibility modules.",
    "نفّذت منطق المعاملات وقواعد التحقق وأجزاء المتابعة للإدارة."
  ],
  [
    "A Laravel backend that keeps sensitive actions auditable and operationally clear.",
    "باك إند Laravel بيخلّي الإجراءات الحساسة قابلة للمراجعة وواضحة للتشغيل."
  ],
  [
    "Transaction logic",
    "منطق المعاملات"
  ],
  [
    "Validation",
    "التحقق"
  ],
  [
    "Audit records",
    "سجلات المراجعة"
  ],
  [
    "Traceable transactions",
    "معاملات قابلة للتتبع"
  ],
  [
    "Safer operations",
    "تشغيل أأمن"
  ],
  [
    "Clear admin monitoring",
    "متابعة واضحة للإدارة"
  ],
  [
    "Transaction-driven backend with auditability and operations-focused monitoring.",
    "باك إند معاملات قابل للمراجعة ومراقبة التشغيل."
  ],
  [
    "Product showcase backend with structured content control and admin management.",
    "باك إند لعرض المنتجات وإدارة المحتوى بشكل منظّم."
  ],
  [
    "Showcase products needed organized data and easier content operations.",
    "عرض المنتجات كان محتاج داتا منظّمة وتحديثات محتوى أسهل."
  ],
  [
    "Built backend structures for products, dashboard controls, and content organization.",
    "بنيت هيكل المنتجات وأدوات لوحة التحكم وتنظيم المحتوى."
  ],
  [
    "A Laravel backend for structured product presentation and maintainable updates.",
    "باك إند Laravel لعرض المنتجات وتحديثها بسهولة."
  ],
  [
    "Product showcase",
    "عرض المنتجات"
  ],
  [
    "CMS dashboard",
    "لوحة CMS"
  ],
  [
    "Structured data",
    "داتا منظّمة"
  ],
  [
    "Cleaner content updates",
    "تحديث محتوى أوضح"
  ],
  [
    "Professional product presentation",
    "عرض احترافي للمنتج"
  ],
  [
    "Scalable data model",
    "داتا قابلة للنمو"
  ],
  [
    "Showcase backend for products, sections, and dashboard-managed content.",
    "باك إند للمنتجات والأقسام والمحتوى اللي بيتدار من لوحة التحكم."
  ],
  [
    "Laravel website backend for service presentation, portfolio sections, and contact flow.",
    "باك إند Laravel لموقع خدمات وأقسام أعمال وخطوات تواصل."
  ],
  [
    "Business website needed professional structure and conversion-focused backend.",
    "موقع الشركة كان محتاج هيكل احترافي وباك إند يساعد في استفسارات العملاء."
  ],
  [
    "Built Laravel pages, content handling, and inquiry flow.",
    "بنيت صفحات Laravel وإدارة المحتوى وخطوات الاستفسار."
  ],
  [
    "Clean service website backend with manageable content sections.",
    "باك إند لموقع خدمات بأقسام محتوى سهلة الإدارة."
  ],
  [
    "Service pages",
    "صفحات الخدمات"
  ],
  [
    "Portfolio sections",
    "أقسام الأعمال"
  ],
  [
    "Contact flow",
    "خطوات التواصل"
  ],
  [
    "Stronger brand delivery",
    "عرض أقوى للهوية"
  ],
  [
    "Better lead flow",
    "وصول أفضل للاستفسارات"
  ],
  [
    "Clear content management",
    "إدارة محتوى واضحة"
  ],
  [
    "Service business backend for content pages and conversion-ready contact journey.",
    "باك إند لموقع خدمات وصفحات محتوى وتجربة تواصل واضحة."
  ],
  [
    "Lost-item reporting backend with structured submissions and support workflow.",
    "باك إند بلاغات المفقودات، بمدخلات منظّمة وخطوات دعم."
  ],
  [
    "Lost-item reporting needed a clean backend process for support teams.",
    "بلاغات المفقودات كانت محتاجة خطوات واضحة لفرق الدعم."
  ],
  [
    "Designed reporting API logic and backend data structure.",
    "صمّمت APIs البلاغات وهيكل الداتا."
  ],
  [
    "Laravel workflow that captures context and improves follow-up.",
    "خطوات Laravel بتجمع تفاصيل البلاغ وتحسّن المتابعة."
  ],
  [
    "Reporting flow",
    "خطوات البلاغ"
  ],
  [
    "Location context",
    "سياق المكان"
  ],
  [
    "Support pipeline",
    "مسار الدعم"
  ],
  [
    "Organized reporting",
    "بلاغات منظّمة"
  ],
  [
    "Faster follow-up",
    "متابعة أسرع"
  ],
  [
    "Cleaner support workflow",
    "دعم أوضح"
  ],
  [
    "Backend concept for lost-item reporting and response operations.",
    "باك إند لفكرة الإبلاغ عن المفقودات وإدارة الردود."
  ],
  [
    "POS backend for invoices, products, and day-to-day sales operations.",
    "باك إند نقاط بيع للفواتير والمنتجات والمبيعات اليومية."
  ],
  [
    "Small business sales workflows needed better structure and speed.",
    "المبيعات في المشروعات الصغيرة كانت محتاجة تنظيم وسرعة أكتر."
  ],
  [
    "Implemented POS-style backend for products, invoices, and reports.",
    "نفّذت باك إند POS للمنتجات والفواتير والتقارير."
  ],
  [
    "Laravel operational backend designed for cashier efficiency.",
    "باك إند Laravel للتشغيل وكفاءة الكاشير."
  ],
  [
    "Cashier flow",
    "خطوات الكاشير"
  ],
  [
    "Invoices",
    "الفواتير"
  ],
  [
    "Daily reports",
    "التقارير اليومية"
  ],
  [
    "Faster sales ops",
    "مبيعات أسرع"
  ],
  [
    "Cleaner invoices",
    "فواتير أوضح"
  ],
  [
    "Operational visibility",
    "وضوح في التشغيل"
  ],
  [
    "POS backend engine for sales operations and invoice reliability.",
    "باك إند كاشير لعمليات البيع وفواتير موثوقة."
  ],
  [
    "Solar services website backend with catalog content, lead flow, and contact conversion.",
    "باك إند موقع خدمات طاقة شمسية للكتالوج والاستفسارات والتواصل."
  ],
  [
    "Solar business website needed a conversion-focused backend flow and manageable content.",
    "موقع الطاقة الشمسية كان محتاج محتوى سهل الإدارة وخطوات تواصل فعّالة."
  ],
  [
    "Built Laravel content structure, service pages, and inquiry conversion workflow.",
    "بنيت هيكل محتوى Laravel وصفحات الخدمات ومسار الاستفسارات."
  ],
  [
    "Delivered a clean Laravel business website backend optimized for leads.",
    "سلّمت باك إند موقع شركة منظّم لاستقبال العملاء المحتملين."
  ],
  [
    "Service catalog",
    "كتالوج الخدمات"
  ],
  [
    "Lead collection",
    "تجميع الاستفسارات"
  ],
  [
    "Contact conversion",
    "التواصل مع العملاء"
  ],
  [
    "Clearer service showcase",
    "عرض أوضح للخدمات"
  ],
  [
    "More qualified leads",
    "استفسارات أنسب"
  ],
  [
    "Professional business presence",
    "حضور احترافي للشركة"
  ],
  [
    "Solar business backend with service catalog and lead conversion flow.",
    "باك إند خدمات طاقة شمسية لكتالوج الخدمات واستفسارات العملاء."
  ],
  [
    "Native PHP tournament platform for teams, groups, and match statistics.",
    "منصة بطولة بـPHP للفرق والمجموعات وإحصائيات المباريات."
  ],
  [
    "Tournament data needed clean structure for teams, groups, and results.",
    "داتا البطولة كانت محتاجة هيكل واضح للفرق والمجموعات والنتائج."
  ],
  [
    "Built PHP/MySQL backend structures and data screens for tournament entities.",
    "بنيت PHP/MySQL وهيكل الداتا وشاشات عرض البطولة."
  ],
  [
    "A practical tournament management backend with clear data hierarchy.",
    "باك إند عملي لإدارة بطولة بتسلسل بيانات واضح."
  ],
  [
    "Teams",
    "الفرق"
  ],
  [
    "Groups",
    "المجموعات"
  ],
  [
    "Statistics",
    "الإحصائيات"
  ],
  [
    "Clear data presentation",
    "عرض واضح للداتا"
  ],
  [
    "Structured tournament views",
    "مشاهد بطولة منظّمة"
  ],
  [
    "Solid PHP practice",
    "تطبيق عملي لـPHP"
  ],
  [
    "Tournament backend platform with structured teams, groups, and statistics data.",
    "باك إند بطولة ببيانات منظّمة للفرق والمجموعات والإحصائيات."
  ],
  [
    "Library management backend for books, inventory, orders, and user records.",
    "باك إند إدارة مكتبة للكتب والمخزون والطلبات وسجلات المستخدمين."
  ],
  [
    "Library operations needed one reliable backend for catalog and order handling.",
    "المكتبة كانت محتاجة باك إند واحد موثوق للكتالوج والطلبات."
  ],
  [
    "Implemented PHP/MySQL modules for inventory, users, and order workflows.",
    "نفّذت أجزاء PHP/MySQL للمخزون والمستخدمين والطلبات."
  ],
  [
    "A complete management backend for library operations and records.",
    "باك إند متكامل لإدارة عمليات المكتبة وسجلاتها."
  ],
  [
    "Inventory",
    "المخزون"
  ],
  [
    "Books",
    "الكتب"
  ],
  [
    "Orders",
    "الطلبات"
  ],
  [
    "Organized inventory",
    "مخزون منظّم"
  ],
  [
    "Cleaner order flow",
    "طلبات أوضح"
  ],
  [
    "Admin-friendly operations",
    "إدارة أسهل"
  ],
  [
    "Library operations backend for inventory, users, and order workflows.",
    "باك إند مكتبة لإدارة المخزون والمستخدمين والطلبات."
  ]
];
